<a href="https://colab.research.google.com/github/csanicola74/Important_Reference_Repo/blob/main/w3resource_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Python through W3Resource.com
Links:
  * [Python](https://www.w3resource.com/python/python-syntax.php)
  * [Exercises](https://www.w3resource.com/python-exercises/)

# Exercise

## #1
Write a Python program to print the following string in a specific format (see the output).

In [ ]:
# Sample String: "Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are"
# Output:
  # Twinkle, twinkle, little star,
	    # How I wonder what you are!
	            #	Up above the world so high,
	            #	Like a diamond in the sky.
  # Twinkle, twinkle, little star,
	    # How I wonder what you are
#################
### REFERENCE ###
#################
# \n_________ = new line
# \n\t_______ = new line and a tab in
# \n\t\t_____ = new line and 2 tabs in
print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\t\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")

Twinkle, twinkle, little star, 
	How I wonder what you are! 
		Up above the world so high, 
		Like a diamond in the sky. 
Twinkle, twinkle, little star, 
	How I wonder what you are!


The print statement (Python 2.6) has been replaced with a print() function(Python 2.6), with keyword arguments to replace most of the special syntax of  the old print statement .
The print() function doesn’t support the “softspace” feature of the old print statement. For example, in Python 2.x, print "A\n", "B" would write "A\nB\n"; but in Python 3.0, print("A\n", "B") writes "A\n B\n".
Initially, you’ll be finding yourself typing the old print x a lot in interactive mode. Time to retrain your fingers to type print(x) instead!
When using the 2to3 source-to-source conversion tool, all print statements are automatically converted to print() function calls, so this is mostly a non-issue for larger projects.

## #2
Write a Python program to find out what version fo Python you are using.

In [ ]:
# version 1
import sys  # Import the sys module to access system-specific parameters and functions

# Print the Python version to the console
print("Python version")

# Use the sys.version attribute to get the Python version and print it
print(sys.version)

# Print information about the Python version
print("Version info.")

# Use the sys.version_info attribute to get detailed version information and print it
print(sys.version_info)


# version 2
import platform
print(platform.python_version())

Python version
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version info.
sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
3.10.12


**Explanation:**
The said code imports the "sys" module and then uses it to print the version of Python currently being used, as well as additional version information.
The first line imports the "sys" module provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter. It is always available.
The second line prints the string "Python version".
The third line prints the version of Python currently being used to the console.
The fourth line prints the string "Version info.".
The fifth line prints version information of the current Python interpreter. It returns a named tuple (version_info) containing the five components of the version number: major, minor, micro, releaselevel, and serial.


## #3
Write a Python program to display the current date and time.

In [ ]:
# Sample Output:
# Current date and time :
# 2014-07-05 14:34:14

# Import the 'datetime' module to work with date and time
import datetime

# Get the current date and time
now = datetime.datetime.now()

# Create a datetime object representing the current date and time

# Display a message indicating what is being printed
print("Current date and time: ")

# Print the current date and time in a specific format
print(now.strftime("%Y-%m-%d %H:%M:%S"))

# Use the 'strftime' method to format the datetime object as a string with the desired format

Current date and time: 
2024-03-21 19:05:37


**Explanation:**
The said code imports the "datetime" module, gets the current date and time, and finally prints it in a formatted string.
The first line import datetime imports the datetime module which supplies classes for manipulating dates and times.
The second line now = datetime.datetime.now() creates a datetime object for the current date and time.
The third line print ("Current date and time : ") prints the string "Current date and time : " to the console.
The fourth line print (now.strftime("%Y-%m-%d %H:%M:%S")) uses the strftime() method of the datetime object to format the date and time as a string in the format "YYYY-MM-DD HH:MM:SS" and prints it to the console.
The strftime() method returns a string representing the date, controlled by an explicit format string. The format codes used in this example are:
%Y: year with century as a decimal number.
%m: month as a zero-padded decimal number.
%d: day of the month as a zero-padded decimal number.
%H: hour (24-hour clock) as a zero-padded decimal number.
%M: minute as a zero-padded decimal number.
%S: second as a zero-padded decimal number.
This code can be useful for logging or timestamping events in a program, or for displaying the current date and time in a user interface.

## #4
Write a Python program that calculates the area of a circle based on the radius entered by the user.

In [ ]:
# Sample Output:
# r = 1.1
# Area = 3.8013271108436504

# Import the 'pi' constant from the 'math' module to calculate the are of a circle
from math import pi

# Prompt the user to input the radius of the circle
r = float(input("Input the radius of the circle: "))

# Calculate the are of the circle using the formula: area = π * r^2
area = pi * r ** 2

# Dispaly the result, including the radius and calculated area
print("The area of the circle with radius " + str(r) + " is: " + str(area))

Input the radius of the circle: 15
The area of the circle with radius 15.0 is: 706.8583470577034


**Explanation:**
The said code calculates the area of a circle based on the radius entered by the user. The code uses the "math" module's pi constant and the "input" function to get the radius from the user, then it uses the formula to calculate the area of the circle.
The first line from math import pi imports the pi constant from the math module, which is the mathematical constant. It represents the ratio of a circle's circumference to its diameter (approximately equal to 3.14).
The second line r = float(input ("Input the radius of the circle : ")) gets the radius of the circle from the user using the input() function. input() function assigns it to the variable r, it's then cast to float, so the user can input decimal number also.
The third line print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2)) uses the formula to calculate the area of the circle (pi*r**2) . Then it concatenates the string and the value of the radius and area using the + operator and prints the final string.
This code is useful to calculate the area of a circle when the radius is known, it can be used in physics and mathematical calculations or in applications that require the area of a circle to be calculated.

## #5
Write a Python program that accepts the user's first and last name and prints them in reverse order with a space between them

In [ ]:
first_name = input("What is your first name: ")
last_name = input("What is your last name: ")
print(last_name + " " + first_name)

What is your first name: Caroline
What is your last name: Sanicola
Sanicola Caroline


**Explanation:**
This code prompts the user to input their first and last name, and then it prints a message that combines the first name and last name in a specific order.
The first line fname = input("Input your First Name : ") gets the user's first name using the input() function and assigns it to the variable 'fname'.
The second line lname = input("Input your Last Name : ") gets the user's last name using the input() function and assigns it to the variable 'lname'.
The third line print ("Hello " + lname + " " + fname) prints a message that combines the last name and first name, concatenating them with the + operator and separated by a space.

## #6
Write a Python program that accepts a sequence of comma-separated numbers from the user and generates a list of a tuple from those numbers.

In [ ]:
# Sample data: 3, 5, 7, 23
# Output:
#   List: ['3', '5', '7', '23']
#   Tuple: ('3', '5', '7', '23')

# Prompt the user to input a sequence of comma-separated numbers and store it in the 'values' variable
values = input("Input some comma-separated numbers: ")

# Split the 'values' string into a list using commas as separators and store it in the 'list' variable
list = values.split(",")

# Convert the 'list' into a tuple and store it in the 'tuple' variable
tuple = tuple(list)

# Print the list
print('List: ', list)

# Print the tuple
print('Tuble: ', tuple)

Input some comma-separated numbers: 5, 15, 84, 111, 64
List:  ['5', ' 15', ' 84', ' 111', ' 64']
Tuble:  ('5', ' 15', ' 84', ' 111', ' 64')


**Explanation:**
The said code prompts the user to input a list of numbers separated by commas. Then it converts the string of numbers into a list and a tuple, and finally it prints both the list and the tuple.
The first line values = input("Input some comma seprated numbers : ") gets a string of numbers separated by commas from the user using the input() function and assigns it to the variable 'values'.
The second line splits the string of numbers into a list of individual numbers using the split() method and assigns it to the variable 'list'. This method takes a separator as input, in this case ',' (comma) and returns a list of substrings that were separated by the separator.
The third line converts the list into a tuple using the tuple() function and assigns it to the variable 'tuple'.
The fourth line prints the list to the console.
The fifth line prints the tuple to the console.

## #7
Write a Python program that accepts a filename from the user and prints the extension of the file.

In [ ]:
# Sample filename: abc.java
# Output: java

# Prompt the user to input a filename and store it in the 'filename' variable
filename = input("Input the Filename: ")

# Split the 'filename' string into a list using the period (.) as a separator and store it in the 'f_extns' variable
f_extns = filename.split(".")

# Print the extension of the file, which is the last element in the 'f_extns' list
print("The extension of the file is: " + repr(f_extns[-1]))

Input the Filename: data.csv
The extension of the file is: 'csv'


**Explanation:**
At first the siad code prompts the user to input a filename and stores it in the variable "filename". It then uses the string method split() to split the value of "filename" by "."(dot) and assigns the result to the variable "f_extns".
The code then uses the index -1 to access the last element of the list "f_extns" which is the file extension and prints the message "The extension of the file is : " followed by the last element.
The repr() function returns a string containing a printable representation of an object.
For example, if the user inputs "abc.txt" as the filename, the code will print "Th e extension of the file is : 'txt'"

## #8
Write a Python program to display the first and last colors from the follow list.

In [ ]:

# color_list = ["Red", "Green", "White", "Black"]

# Create a list called 'color_list' containing color names
color_list = ["Red", "Green", "White", "Black"]
# Print the first and last elements of the 'color_list' using string formatting
# The '%s' placeholders are filled witht he values of 'color_list[0]' (Red) and 'color_list[-1]' (Black)
print("%s %s" % (color_list[0], color_list[-1]))

Red Black


**Explanation:**
The said code creates a list named "color_list" which includes four different colors, "Red", "Green", "White", and "Black". Then, it utilizes string formatting to print the first (Index 0) and the last (Index -1) color of the list together with a space in between. The output would be "Red Black".

## #9
Write a Python program to display the examination schedule. (extract the date from exam_st_date).

In [ ]:
# exam_st_date = (11, 12, 2014)
# Sample Output: The examination will start from: 11/12/2014

# Define a tuple called 'exam_st_date' containing the exam start date in the format (day, month, year)
exam_st_date = (11, 12, 2014)

# Print the exam start date using string formatting
# The '%i' placeholders are filled with the values from the 'exam_st_date' tuple
print("The examination will start from: %i/%i/%i" % exam_st_date)

The examination will start from: 11/12/2014


**Explanation:**
The said code creates a tuple called "exam_st_date" containing three integers: 11, 12, and 2014. It then uses string formatting to print a string that states "The examination will start from :" followed by the integers in the tuple in the order they appear, formatted as day/month/year. The placeholders %i are used to format the integers.
The output would be: "The examination will start from : 11 / 12 / 2014".

## #10
Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn


In [ ]:
# Sample value of n is 5
# Expected Result: 615

# Prompt the user to input an integer and store it in the variable 'a'
a = int(input("Input an integer: "))

# Create new integers 'n1', 'n2', and 'n3' by concatenating 'a' with itself one, two, and three times, respectively
n1 = int("%s" % a)              # Convert 'a' to an integer
n2 = int("%s%s" % (a, a))       # Concatenate 'a' with iteself and convert to an integer
n3 = int("%s%s%s" % (a, a, a))  # Concatenate 'a' with itself twice and convert to an integer

# Calculate the sum of 'n1', 'n2', and 'n3' and print the result
print(n1 + n2 + n3)

Input an integer: 64
652992


**Explanation:**
The said code prompts the user to input an integer, which is then stored in the variable "a".
There after the first variable n1 is created by converting the input integer "a" to a string and then back to an integer.
The second variable n2 is created by concatenating two copies of the input integer "a" as a string and then converting that string to an integer.
The third variable n3 is created by concatenating three copies of the input integer "a" as a string and then converting that string to an integer.
Finally, the code sums the three variables n1, n2 and n3 and print the result.

## #11
Write a Python program to print the documents (syntax, description etc.) of Python built-in function(s).

In [ ]:
# Sample function: abs()
# Expected Result:
# abs(number) -> number
# Return the absolute value of the argument

# Print the docstring (documentation) of the 'abs' function
print(abs.__doc__)

Return the absolute value of the argument.


Python Docstring:
A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition. Such a docstring becomes the __doc__ special attribute of that object.
All modules should normally have docstrings, and all functions and classes exported by a module should also have docstrings. Public methods (including the __init__ constructor) should also have docstrings.

## #12
Write a Python program that prints the calendar for a given month and year.

In [ ]:
# Note: Use 'calendar' module

# Import the 'calendar' module
import calendar

# Prompt the user to input the year and month
y = int(input("Input the year: "))
m = int(input("Input the month: "))

# Print the calendar for the specified year and month
print(calendar.month(y, m))

Input the year: 2024
Input the month: 3
     March 2024
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



**Explanation:**
The said code imports the calendar module, which allows you to output calendars like the Unix cal program, and provides additional useful functions related to the calendar. It then asks the user to input an integer for the year and month.
The code then uses the month() function from the calendar module, which takes the year and month as arguments and returns a string containing an ASCII calendar for that month of that year.

## #13
Write a Python program to print the following 'here document'.

In [ ]:
# Sample string:
# a string that you "don't" have to escape
# This
# is a ..... multi-line
# heredoc string ------> example

print("""
a string that you "don't" have to escape
This
is a ....... multi-line
heredoc string --------> example
""")


a string that you "don't" have to escape
This
is a ....... multi-line
heredoc string --------> example



**Explanation:**
A here document (or "heredoc") is a way of specifying a text block, preserving the line breaks, indents, and other whitespace within the text. The said code uses triple quotes to define a multi-line string, also known as a heredoc string. It allows the string to span multiple lines without the need to escape newline characters.
The output will be the string exactly as it appears in the code, including the newline characters.

## #14
Write a Python program to calculate the number of days between two dates.

In [ ]:
# Sample dates: (2014, 7, 2), (2014, 7, 11)
# Expected output: 9 days

# Import the 'date' class from the 'datetime' module
from datetime import date

# Define a start date as July 2, 2014
f_date = date(2014, 7, 2)

# Define an end date as July 11, 2014
l_date = date(2014, 7, 11)

# Calculate the difference between the end date and start date
delta = l_date - f_date

# Print the number of days in the time difference
print(delta.days)

9


**Explanation:**
This script imports the "date" class from the "datetime" module.
It then creates two date objects (<class 'datetime.date'>), 'f_date 'and 'l_date'.
The script then calculates the difference between these two dates and stores it in a variable called 'delta'.
The 'delta' variable is then printed, specifically the attribute "days" which returns the number of days between the said two dates.
In this case, the output would be 9, as there are 9 days between July 2nd and July 11th in 2014.

## #15
Write a Python program to get the volume of a sphere with radius six

In [ ]:
# Define the value of pi
pi = 3.1415926535897931

# Define the radius of the sphere
r = 6.0

# Calculate the volume of the sphere using the formula
V = 4.0/3.0 * pi * r**3

# Print the calculated volume of the sphere
print('The volumne of the sphere is: ', V)

The volumne of the sphere is:  904.7786842338603


**Explanation:**
The said code assigns the value of pi as 3.1415926535897931 to the variable "pi" and 6.0 to the variable "r". The code uses the formula V = 4/3 * pi * r^3 to calculate the volume of a sphere. Volume of the sphere is stored in the variable "V".
It then prints the message "The volume of the sphere is:" followed by the volume of the sphere using print statement.
In this case, the code will output "The volume of the sphere is: 904.7786842338603".

## #16
Write a Python program to calculate the difference between a given number and 17.

In [ ]:
# If the number is greater than 17, return twice the absolute difference.

# Define a function named "difference" that takes an integer parameter "n"
def difference(n):
  # Check if n is less than or equal to 17
  if n <= 17:
    # If n is less than or equal to 17, return the absolute difference between 17 and n
    return 17 - n
  else:
    # If n is greater than 17, return the absolute difference between n and 17 multiplied by 2
    return (n - 17) * 2

# Call the "difference" function with the argument 22 and print the result
print(difference(22))

# Call the "difference" function with the argument 14 and print the result
print(difference(14))

10
3


**Explanation:**
The said script defines a function called 'difference' that takes input(n) as an argument. Using an if-else statement the function checks whether the input value of n is less than or equal to 17. If the input value of n is less than or equal to 17, the function will return the difference of 17 - n. If the input value of n is greater than 17, the function will return double the difference of n - 17.
Now the script calls the function twice with the input values of 22 and 14, respectively.
In the first case the input is greater than 17, so the function returns (22-17)*2 = 10. Therefore, the script will print 10.
In the second case the input value is less than or equal to 17, so the function returns 17-14 = 3. Therefore, the script will print 3.

## #17
Write a Python program to test whether a number is within 100 of 1000 or 2000.

In [ ]:
# Define a function named "near_thousand" that takes an integer parameter "n"
def near_thousand(n):
  # Check if the absolute difference between 1000 and n is less than or equal to 100
  # OR check if the absoluate difference between 2000 and n is less than or equal to 100
  return ((abs(1000 - n) <= 100) or (abs(2000 - n) <= 100))

# Call the "near_thousand" function with the argument 1000 and print the result
print(near_thousand(1000))

# Call the "near_thousand" function with the argument 900 and print the result
print(near_thousand(900))

# Call the "near_thousand" function with the argument 800 and print the result
print(near_thousand(800))

# Call the "near_thousand" function with the argument 2200 and print the result
print(near_thousand(2200))

True
True
False
False


**Explanation:**
The said script defines a function called near_thousand(n) that takes an integer as an argument and returns True if the input is within 100 of either 1000 or 2000, and False otherwise. The function uses the abs() function, which returns the absolute value of a number, to determine the difference between the input and 1000 or 2000.
Now the script calls the function four time with the input values of 1000, 900, 800 and 2200 respectively.
When the input value is 1000, it returns True because the difference between 1000 and 1000 is 0, which is less than 100.
When the input value is t 900, it returns True because the difference between 900 and 1000 is 100, which is less than 100.
When the input value is 800, it returns False because the difference between 800 and 1000 is 200, which is not less than or equal to 100.
When the input value is 2200, it returns False because the difference between 2200 and 2000 is 200, which is not less than or equal to 100.

## #18
Write a Python program to calculate the sum of three given numbers.

In [ ]:
# If the values are equal, return three times their sum.

# Define a function named "sum_thrice" that takes three integer parameters: x, y, and z
def sum_thrice(x, y, z):
  # Calculate the sum of x, y, and z
  sum = x + y + z

  # Check if x, y, and z are all equal (all three numbers are the same)
  if x == y == z:
    # If they are equal, triple the sum
    sum = sum * 3

  # Return the final sum
  return sum

# Call the "sum_thrice" function with the arguments (1, 2, 3) and print the result
print(sum_thrice(1, 2, 3))

# Call the "sum_thrice" function with the arguments (3, 3, 3) and print the result
print(sum_thrice(3, 3, 3))

6
27


**Explanation:**
The said script defines a function called sum_thrice(x, y, z) that takes three integers as arguments and returns their sum. The function, however, multiplies the sum by 3 if all three integers are equal.
Now the script calls the function twice with the input values (1,2,3) and (3,3,3).
Whenever 1, 2, and 3 are input values, the three inputs are not equal, so it returns 6.
Whenever 3, 3, and 3 are input values, the three inputs are equal so the function multiplies the sum by 3 and returns 27.
Depending on the inputs, the if statement holds true only if x == y == z, otherwise it holds False.

## #19
Write a Python program to get a newly-generated string from a given string where "ls" has been added to the front.

In [ ]:
# Return the string unchanged if the given string already begins with "ls"

# Define a function named "new_string" that takes a string parameter called "text"
def new_string(text):
  # Check if the length of the "text" is greater than or equal to 2 and if the first two characters of "text" are "Is"
  if len(text) >= 2 and text[:2] == "Is":
    # If the conditions are met, return the original "text" unchanged
    return text
  else:
    # If the conditions are not met, prepend "Is" to the "text" and return the modified string
    return "Is" + text

# Call the "new_string" function with the argument "Array" and print the result
print(new_string("Array"))

# Call the "new_string" function with the argument "IsEmpty" and print the result
print(new_string("IsEmpty"))

IsArray
IsEmpty


**Explanation:**
The said script defines a function "new_string(text)" takes a string as an argument, and checks whether the string's length is greater than or equal to 2 and the first two characters of the string are "Is". If both conditions are true, the function returns the original string. Otherwise, the function returns a new string "Is" concatenated with the original string.
The first print statement will display "IsArray" and the second will display "IsEmpty".

## #20
Write a Python program that returns a string that is n (non-negative integer) copies of a given string.

In [ ]:
# Define a function named "larger_string" that takes two parameters, "text" and "n"
def larger_string(text, n):
    # Initialize an empty string variable named "result"
    result = ""

    # Use a for loop to repeat the "text" "n" times and concatenate it to the "result"
    for i in range(n):
        result = result + text

    # Return the final "result" string
    return result

# Call the "larger_string" function with the arguments 'abc' and 2, then print the result
print(larger_string('abc', 2))

# Call the "larger_string" function with the arguments '.py' and 3, then print the result
print(larger_string('.py', 3))

abcabc
.py.py.py


**Explanation:**
The said code defines a function called "larger_string" which takes two arguments: "text" and "n". The function will concatenate the "text" argument "n" number of times and return the result as a new string.
The function starts by initializing an empty string variable called "result". Then, it uses a for loop to iterate over a range of numbers, starting from 0 and ending at "n". On each iteration, the function takes the current value of "result" and adds the "text" argument to it, effectively concatenating the "text" argument with itself "n" times.
The last two lines of code call the function, with different arguments.
In the first case the function takes 'abc' as text and 2 as the n, the function will concatenate 'abc' two times and return 'abcabc'
In the second case the function takes '.py' as text and 3 as the n, the function will concatenate '.py' three times and return '.py.py.py'
The function returns the concatenated string as the final output.

## #21
Write a Python program that determines whether a given number (accepted from the user) is even or odd, and prints an appropriate message to the user

In [ ]:
# Prompt the user to enter a number and convert the input to an integer
num = int(input("Enter a number: "))

# Calculate the remainder when the number is divided by 2
mod = num % 2

# Check if the remainder is greater than 0, indicating an odd number
if mod > 0:
  # Print a message indicating that the number is odd
  print("this is an odd number.")
else:
  # Print a message indicating that the number is even
  print("this is an even number.")

Enter a number: 5
this is an odd number.


**Explanation:**
The said code prompts the user to input a number, then converts the input to an integer and assigns it to the variable 'num'. Then it calculates the remainder of 'num' and 2 and assigns it to the variable 'mod'. Next, it checks the value of 'mod'. If the value of 'mod' is greater than 0, it prints "This is an odd number." otherwise prints "This is an even number.".

## #22
Write a Python program to count the number 4 in a given list.

In [ ]:
# Define a function called list_count_4 that takes a list of numbers (nums) as a parameter.
def list_count_4(nums):
  # Initialize a variable count to keep track of the count of occurrences of the number 4.
  count = 0

  # Iterate through each element (num) in the input list (nums).
  for num in nums:
    # Check if the current element (num) is equal to 4.
    if num == 4:
      # If the element is 4, increment the count by 1.
      count = count + 1

  # Return the final count after iterating through the list.
  return count

# Call the list_count_4 function with two different input lists and print the results.
print(list_count_4([1, 4, 6, 7, 4]))  # Output: 2 (There are two occurrences of 4 in the list.)
print(list_count_4([1, 4, 6, 4, 7, 4]))  # Output: 3 (There are three occurrences of 4 in the list.)

2
3


**Explanation:**
The said code defines a function called "list_count_4" that takes a list of numbers as its argument, "nums". Inside the function, it initializes a variable "count" to zero. Next, it uses a for loop to iterate through each element in the "nums" list. For each iteration, it checks if the current element i.e. num is equal to 4, if true it increments the "count" by 1. After the for loop completes, the function returns the final "count" of how many times the number 4 appears in the list.
The last two lines of code call the function, with the input values ([1, 4, 6, 7, 4]) and ([1, 4, 6, 4, 7, 4]) and print the results.
The first call will return 2, and the second call will return 3.

## #23
Write a Python program to get n (non-negative integer) copies of the first 2 characters of a given string.

In [ ]:
# Return n copies of the whole string if the length is less than 2.

# Define a function called substring_copy that takes two parameters: text (a string) and n (an integer).
def substring_copy(text, n):
  # Set the initial value of flen (substring length) to 2.
  flen = 2

  # Check if flen is greater than the length of the input text.
  if flen > len(text):
    # If flen is greater, set it to the length of the text to avoid going out of bounds.
    flen = len(text)

  # Extract a substring of length flen from the beginning of the text.
  substr = text[:flen]

  # Initialize an empty string result to store the concatenated substrings.
  result = ""

  # Iterate n times to concatenate the substring to the result.
  for i in range(n):
    result = result + substr

  #Return the final result after concatenating substrings.
  return result

# Call the substring_copy function with two different inputs and print the results
print(substring_copy('abcdef', 2)) # Output: "abab" (substring "ab" repeated 2 times)
print(substring_copy('p', 3)) # Output: "ppp" (substring "p" repeated 3 times)

abab
ppp


**Explanation:**
The said code defines a function called "substring_copy" that takes two arguments, a string "text" and an integer "n".
Inside the function, it creates a variable "flen" and assigns it the value of 2. Next, it checks whether the value of "flen" is greater than the length of the input string "text". If true it assigns the value of len(text) to "flen" otherwise it creates a variable "substr" and assigns it the value of the first two characters of the input string "text" using string slicing method.
Then it creates an empty string called "result" and uses a for loop to iterate "n" times. During each iteration it concatenates the "substr" to the "result" string. Finally, it returns the value of the "result" variable.
The last two lines of code call the function, with the input values ('abcdef', 2) and ('p', 3) and print the results. The first call will return 'abab' and the second will return 'ppp'.


## #24
Write a Python program to test whether a passed letter is a vowel or not.

In [ ]:
# Define a function called is_vowel that takes one parameter: char (a character).
def is_vowel(char):
  # Define a string called all_vowels containing all lowercase vowel characters.
  all_vowels = 'aeiou'

  # Check if the input character (char) is present in the all_vowels string.
  return char in all_vowels

# Call the is_vowel function with two different characters and print the results
print(is_vowel('c')) # Output: False (character 'c' is not a vowel)
print(is_vowel('e')) # Output: True (character 'e' is a vowel)

False
True


**Explanation:**
The said code defines a function called "is_vowel" which takes in one parameter "char". First, the function declares a variable "all_vowels" containing all lowercase vowels. The function then uses the "in" operator to check whether the value of "char" parameter is present within the "all_vowels" string, and returns the result.
In the last two lines the code call the function "is_vowel" twice, with the input values 'c' and 'e' and print the results.
In the first case, False will be returned, while in the second case, True will be returned.

## #25
Write a Python program that checks whether a specified value is contained within a group of values.

In [ ]:
# Define a function called is_group_member that takes two parameters: group_data (a list) and n (an integer)
def is_group_member(group_data, n):
  # Iterate through the elements (values) in the group_data list.
  for value in group_data:
    # Check if the current value is equal to the given integer, n.
    if n == value:
      return True # If found, return True.
  return False # If the loop completes and no match is found, return False.

# Call the is_group_member function with two different lists and integers, and print the results.
print(is_group_member([1, 5, 8, 3], 3)) # Output: True (3 is in the list)
print(is_group_member([5, 8, 3], -1)) # Output: False (-1 is not in the list)

True
False


**Explanation:**
The said code defines a function called "is_group_member" that takes two arguments "group_data" a list and an integer "n". First, the function declares a for loop to iterate through each element in the "group_data" list. When the current element (value) value matches the value of "n", it returns True, which means the input integer is present in the "group_data" list. The function returns False if the for loop fails to find a match, meaning the input integer does not exist in "group_data".
In the last two lines the code call the function "is_group_member" twice, with the input values ([1, 5, 8, 3], 3) and ([5, 8, 3], -1) and print the results.
In the first case, False will be returned, while in the second case, True will be returned.

## #26
Write a Python program to create a histogram from a given list of integers

In [ ]:
# Define a function called histogram that takes a list of items as a parameter.
def histogram(items):
  # Iterate through the items in the list.
  for n in items:
    output = '' # Initialize an empty string called output.
    times = n   # Set the times variable to the value of n

    # Use a while loop to append '*' to the output string 'times' number of times
    while times > 0:
      output += '*'
      times = times - 1 # Decrement the times variable

    # Print the resulting output string.
    print(output)

# Call the histogram function with a list of numbers and print the histogram
histogram([2, 3, 6, 5])

**
***
******
*****


**Explanation:**
The function "histogram" takes a parameter "items ", a list of integers. To iterate through each item in the "items" list, the function uses a for loop. For each iteration, it creates a varaible "output", and assigns the current element (n) of the loop to the variable "times".
Then it uses a while loop which will run as long as the value of "times" is greater than 0. Inside the while loop, it concatenates an asterisk (*) character to the "output" variable and decrements the value of "times" by 1 at each iteration. After the while loop completes, it prints the final value of "output" variable.
The last line of code calls the "histogram" function with a list of integers ([2, 3, 6, 5]) as an argument, it will print a histogram of asterisks, where the number of asterisks corresponds to the value of the integers in the list.

## #27
Write a Python program that concatenates all elements in a list into a string and returns it

In [ ]:
# Define a function called concatenate_list_data that takes a list as a parameter.
def concatenate_list_data(lst):
  result = '' # Initialize an empty string called result.

  # Iterate through the elements in the list.
  for element in lst:
    result += str(element) # Convert each element to a string and concatenate it to the result

  return result # Return the concatenated string.

# Call the concatenate_list_data function with a list of numbers and print the result.
print(concatenate_list_data([1, 5, 12, 2]))

15122


**Explanation:**
The said code defines a function called "concatenate_list_data" that takes a list as its argument. Inside the function, it creates an empty string variable called "result".
Then it uses a for loop to iterate through each element in the input list. For each iteration, it converts the current element to a string using the str() function and concatenates it to the "result" variable.
Upon completion of the for loop, the variable "result" is returned.
The last line of code calls the "concatenate_list_data" function with a list of integers ([1, 5, 12, 2]) as an argument, it will print a string "15122".

## #28
Write a Python program to print all even numbers from a given list of numbers in the same order and stop printing any after 237 in the sequence.

In [ ]:
# Define a list of numbers.
numbers = [
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958,743, 527
]

# Iterate through the numbers in the list.
for x in numbers:
  if x == 237:
      print(x) # Print the number if its 237
      break # Exit the loop if 237 is found.
  elif x % 2 == 0:
      print(x) # Print the number if its even.

386
462
418
344
236
566
978
328
162
758
918
237


**Explanation:**
The said code defines a list called "numbers" with a set of integers. Then it uses a for loop to iterate through each element in the "numbers" list.
For each iteration, it checks if the current element is equal to 237, if true it prints the current element and exit the loop using the "break" statement.
If the current element is not equal to 237, it checks if the current element is even, if true it prints the current element.
Using this logic, the code will only print the number 237 and even numbers of the list. If 237 was not found in the list, the code will print all the even numbers in the list.

## #29
Write a Python program that prints out all colors from color_list_1 that are not present in color_list_2.

In [ ]:
# Create two sets, color_list_1 and color_list_2.
color_list_1 = set(["White", "BlacK", "Red"])
color_list_2 = set(["Red", "Green"])

# Print the original elements of the sets.
print("Original set elements:")
print(color_list_1)
print(color_list_2)

# Calculate and print the difference of color_list_1 and color_list_2.
print("\nDifference of color_list_1 and color_list_2:")
print(color_list_1.difference(color_list_2))

# Calculate and print the difference of color_list_2 and color_list_1.
print("\nDifference of color_list_2 and color_list_1:")
print(color_list_2.difference(color_list_1))

Original set elements:
{'Red', 'BlacK', 'White'}
{'Green', 'Red'}

Difference of color_list_1 and color_list_2:
{'BlacK', 'White'}

Difference of color_list_2 and color_list_1:
{'Green'}


**Explanation:**
The said code defines two sets called "color_list_1" and "color_list_2" containing string elements.
The elements of both sets are then printed.
After that, it uses the difference() method on "color_list_1" and passes "color_list_2" as an argument to it. This method returns the elements that are in the "color_list_1" but not in "color_list_2".
Again it uses the difference() method on "color_list_2" and passes "color_list_1" as an argument to it. This method returns the elements that are in the "color_list_2" but not in "color_list_1".
The output of the code will be:
Original set elements:
{'Red', 'White', 'Black'}
{'Red', 'Green'}
Differenct of color_list_1 and color_list_2:
{'White', 'Black'}
Differenct of color_list_2 and color_list_1:
{'Green'}

## #30
Write a Python program that will accept the base and height of a triangle and compute its area.

In [ ]:
# Prompt the user to input the base and height of a triangle as integers.
b = int(input("Input the base: "))
h = int(input("Input the height: "))

# Calculate the area of the triangle using the formula: (base * height) / 2
area = b * h / 2

# Print the calculated area of the triangle.
print("area = ", area)

Input the base: 16
Input the height: 8
area =  64.0


**Explanation:**
The said code prompts the user to input an integer value for the base and height of a triangle. Stores these values in variables "b" and "h" respectively. It then calculates the area of the triangle by multiplying the base and height and dividing the result by 2 and assigns the result to the variable "area". Finally, it prints the calculated area.

## #31
Write a Python program that computes the greatest common divisor (GCD) of two positive integers

In [ ]:
# Define a function to calculate the greatest common divisor (GCD) of two numbers.
def gcd(x, y):
  # Initialize gcd to 1.
  gcd = 1

  # Check if y is a divisor of x (x is divisible by y)
  if x % y == 0:
    return y

  # Iterate from half of y down to 1.
  for k in range(int(y / 2), 0, -1):
    # Check if both x and y are divisible by k.
    if x % k == 0 and y % k == 0:
      # Update the GCD to the current value of k and exit the loop.
      gcd = k
      break

  # Return the calculated GCD
  return gcd

# Print the GCD of specific pairs of numbers.
print("GCD of 12 & 17 =", gcd(12, 17))
print("GCD of 4 & 6 =", gcd(4, 6))
print("GCD of 336 & 360 =", gcd(336, 360))

GCD of 12 & 17 = 1
GCD of 4 & 6 = 2
GCD of 336 & 360 = 24


**Explanation:**

Here is a simple implementation of the Euclidean algorithm for finding the greatest common divisor (GCD) of two integers.

The function "gcd(x,y)" starts by initializing the variable "gcd" to 1, and then checks if "x" is divisible by "y". If it is, it returns "y" as the GCD.

If "x" is not divisible by "y", it enters a "for" loop. In each iteration, it checks if "k" is a common divisor of "x" and "y", and if it is, it assigns the value of k to the variable "gcd" and breaks out of the loop. Finally, the function returns the value of GCD of "x" and "y".

Last three print statements of the said code call the function with different inputs, and print the output as "GCD of 12 & 17 = 1", "GCD of 4 & 6 = 2" and "GCD of 336 & 360 = 24".

## #32
Write a Python program to find the least common multiple (LCM) of two positive integers

In [ ]:
# Define a function 'lcm' that calculates the least common multiple (LCM) of two numbers, 'x' and 'y'.
def lcm(x, y):
  # Compare 'x' and 'y' to determine the larger number and store it in 'z'.
  if x > y:
    z = x
  else:
    z = y

  # Use a 'while' loop to find the LCM.
  while True:
    # Check if 'z' is divisible by both 'x' and 'y' with no remainder.
    if (z % x == 0) and (z % y == 0):
      # If both conditions are met, 'z' is the LCM, so store it in 'lcm' and break the loop.
      lcm = z
      break
    # If the conditions are not met, increment 'z' and continue checking.
    z += 1

  # Return the calculated LCM.
  return lcm

# Calculate and print the LCM of 4 and 6
print(lcm(4, 6))
# Calculate and print the LCM of 15 and 17.
print(lcm(15, 17))

12
255


**Explanation:**

The said code defines a function "lcm(x, y)" that takes two integers as its argument and will return the least common multiple (LCM) of two arguments, "x" and "y".

First, the function determines which number is larger and assigns that value to a variable named "z". It then enters a loop that continues indefinitely (while(True)) until the LCM is found.

Inside the loop, the code checks if the current value of "z" is divisible by both "x" and "y" (if((z % x == 0) and (z % y == 0))). If it is true then the LCM is assigned to the variable "lcm" and the loop is broken. Otherwise, the value of "z" is incremented by 1 and the check is repeated.

Finally, the function returns the value of "lcm" as the output.

After the function definition, the code calls the function twice, first with the arguments 4 and 6, then with the arguments 15 and 17 and prints the results.

## #33
Write a Python program to sum three given integers. However, if two values are equal, the sum will be zero.

In [ ]:
# Define a function 'sum_three' that takes three integer inputs: x, y, and z.
def sum_three(x, y, z):
  # Check if any of the two input calues are equal. If so, set 'sum' to 0.
  if x == y or y == x or x == z:
    sum = 0
  else:
    # If all three input values are distinct, calculate the sum of x, y, and z.
    sum = x + y + z
  # Return the calculated sum.
  return sum

# Test the 'sum_three' function with different sets of input values and print the results.
print(sum_three(2, 1, 2))
print(sum_three(3, 2, 2))
print(sum_three(2, 2, 2))
print(sum_three(1, 2, 3))

0
7
0
6


**Explanation:**

The said code defines a function "sum_three(x, y, z)" that takes three integers as its argument and returns their sum.

The function first checks if any of the three integers (x,y,z) are equal, if any two or three integers are equal, it assigns 0 to the variable "sum".

Otherwise, it assigns the sum of the three integers to the variable "sum".

Finally, it returns the value of "sum".

At the end, the function is called four times with different inputs and prints the sum of the inputs.


## #34
Write a Python program to sum two given integers. However if the sum is between 15 and 20 it will return 20.

In [ ]:
# Define a function 'sum' that takes two integer inputs: x and y
def sum(x, y):
  # Calculate the sum of x and y and store it in the 'sum' variable
  sum = x + y
  # Check if the calculated sum is within the range [15, 20) (inclusive on 15, exclusive on 20).
  if sum in range(15, 20):
    # If the sum is within the range, return 20.
    return 20
  else:
    # If the sum is outside the range, return the calculated sum.
    return sum

# Test the 'sum' function with different sets of input values and print the results
print(sum(10, 6))
print(sum(10, 2))
print(sum(10, 12))

20
12
22


**Explanation:**

The said code defines a function "sum(x, y)" that takes two integers as arguments and returns their sum.

It first calculates the sum of the two integers and assigns it to the variable "sum".

Then it checks whether the value of "sum" is in the range of 15 to 20 (inclusive) using the in-built Python function "range()".

If the value of "sum" is in the range of 15 to 20, the function returns 20 otherwise, it returns the value of "sum".

At the end, the function is called three times with different inputs and prints the sum of the inputs.

## #35
Write a Python program that returns true if the two given integer values are equal or their sum or difference is 5.

In [ ]:
# Define a function 'test_number5' that takes two integer inputs: x and y.
def test_number5(x, y):
  # Check if any of the following conditions are met:
  # 1. x is equal to y.
  # 2. The absolute difference between x and y is equal to 5
  # 3. The sum of x and y is equal to 5.
  if x == y or abs(x - y) == 5 or (x + y) == 5:
    # If any of the conditions are met, return True.
    return True
  else:
    # If none of the conditions are met, return False.
    return False

# Test the 'test_number5' function with different sets of input values and print the results.
print(test_number5(7, 2))
print(test_number5(3, 2))
print(test_number5(2, 2))
print(test_number5(7, 3))
print(test_number5(27, 53))

True
True
True
False
False


**Explanation:**

The said code defines a function "test_number5(x, y)" that takes two integers "x" and "y" as arguments and check if they are equal, or if their sum or difference is equal to 5. If any of these conditions is true, the program would return "True", otherwise, it would return "False".

At the end, the function is called five times with different inputs and prints the outputs of the inputs.

## #36

In [ ]:
# Define a function 'add_numbers' that takes two arguments: a and b.
def add_numbers(a, b):
  # Check if both 'a' and 'b' are integers using the 'isinstance' function.
  if not (isinstance(a, int) and isinstance(b, int)):
    # If either 'a' or 'b' is not an integer, return an error message.
    return "Inputs must be integers!"
  # If both 'a' and 'b' are integers, return their sum.
  return a + b

# Test the 'add_numbers' function with various input values and print the results
print(add_numbers(10, 20))    # Valid: Both inputs are integers, and it returns the sum
print(add_numbers(10, 20.34)) # Invalid: One of the inputs is a float, so it returns an error
print(add_numbers('5', 6))    # Invalid: One of the inputs is a string, so it returns an error
print(add_numbers('5', '6'))  # Invalid: Both inputs are strings, so it returns an error

30
Inputs must be integers!
Inputs must be integers!
Inputs must be integers!


**Explanation:**

The said code defines a function called "add_numbers(a, b)" that takes two integers "a" and "b" as arguments. The function first checks if "a" and "b" are both instances of the "int" data type using the "isinstance" function. If either "a" or "b" is not an integer, the function returns the string "Inputs must be integers!"

Finally the code calls the function four times with different arguments, passing i) two integers, ii) an integer and a float, iii) a string and an integer and iv) two strings.

It will return the sum of the integers passed in the first call. For the second, third and fourth calls will return the string "Inputs must be integers!" as the inputs passed are not integers.

## #37
Write a Python program that displays your name, age, and address on three different lines.

In [ ]:
# Define a function 'personal_details'.
def personal_details():
  # Define variables 'name' and 'age' and assign values to them.
  name, age = "Caroline", 30
  # Define a variable 'address' and assign a value to it
  address = "New York, United States"
  # Print the personal details using string formatting.
  print("Name: {}\nAge: {}\nAddress: {}".format(name, age, address))

# Call the 'personal_details' function to display the details.
personal_details()

Name: Caroline
Age: 30
Address: New York, United States


In [ ]:
# EXTRA - my design

# Define the function 'personal_details'
def personal_details_2():
  # ask the user for their name, age, and address
  user_name = input("What is your name: ")
  user_age = int(input("What is your age: "))
  user_address = input("What is your address: ")
  print("\nBelow are your personal details.\nName: {}\nAge: {}\nAddress: {}".format(user_name, user_age, user_address))

# Call the 'personal_details' function to display the details
personal_details_2()

What is your name: Caroline
What is your age: 30
What is your address: New York, USA

Below are your personal details.
Name: Caroline
Age: 30
Address: New York, USA


**Explanation:**

The said code defines a function called "personal_details" which does not take any arguments. Within the function, three variables are defined: "name" is assigned the string "Simon", "age" is assigned the integer 19, and "address" is assigned the string "Bangalore, Karnataka, India".

The function then uses the print() function to output the values of these three variables in a formatted string. The curly braces {} are placeholders for the values that will be passed through the .format() method.

Finally the function is called at the end of the code and prints the values of name, age and address.

## #38
Write a Python program to solve (x + y) * (x + y).

In [ ]:
# Define variables 'x' and 'y' and assign values to them.
x, y = 4, 3
# Calculate the result by squaring the sum of 'x' and 'y'
result = x * x + 2 * x * y + y * y
# Print the result with a formatted message
print("({} + {}) ^ 2) = {}".format(x, y, result))

(4 + 3) ^ 2) = 49


**Explanation:**

The said Python code assigns the value 4 to the variable x and 3 to the variable y. Then it defines the variable "result" as the result of the mathematical expression (x^2 + 2xy + y^2).

The print statement then uses string formatting to output the final result of the expression and the values of x and y in the string "(x + y) ^ 2 = result".

The final output will be (4 + 3) ^ 2 = 49.

## #39
Write a Python program to compute the future value of a specified principal amount, rate of interest, and number of years.

The formula for future value with compount interest is FV = P(1 + r/n)^nt.
FV = the future value;
P = the principal;
r = the annual interest rate expressed as a decimal;
n = the number of times interest is paid each year;
t = time in years

In [ ]:
# Define the principal amount (initial investment).
amt = 10000
# Define the annual interest rate as a percentage
int = 3.5
# Define the number of years
years = 7
# Calculate the future value of the investment using the compound interest formula.
future_value = amt * ((1 + (0.01 * int)) ** years)
# Round the future value to two decimal places and print it
print(round(future_value, 2))

12722.79


**Explanation:**

The said Python code calculates the future value of an investment of $10000, with an interest rate of 3.5% and a number of years of 7.

A variable "amt" is defined and assigned the value of 10000.
Another variable "int" is defined and assigned the value of 3.5.
A variable "years" is defined and assigned the value of 7.
A variable "future_value" is defined and assigned the value of the calculation of the future value of the investment. The calculation is done by the mathematical formula amt*((1+(0.01*int)) ** years).
The final value is then rounded off to 2 decimal places and printed using the round() and print() function.
The final output will be 12722.79 which is the future value of the investment after 7 years with an interest rate of 3.5%.

## #40
Write a Python program to calculate the distance between the points (x1, y1) and (x2, y2).

In [ ]:
# Import the math module to use the square root function.
import math

# Define the coordinates of the first point (p1) as a list.
p1 = [4, 0]

# Define the coordinates of the second point (p2) as a list.
p2 = [6, 6]

# Calculate the distance between the two points using the distance formula.
# The formula computes the Euclidean distance in a 2D space.
distance = math.sqrt(((p1[0] - p2[0]) ** 2) + ((p1[1] - p2[1]) ** 2))

# Print the calculated distance
print(distance)

6.324555320336759


**Explanation:**

The said code calculates the Euclidean distance between two points in a 2-dimensional coordinate system.

It starts by importing the "math" module which is used to calculate the square root of the given expression.
Then it defines two variables p1 and p2 which are lists containing the x and y coordinates of two points. In this case, the first point is at coordinates (4, 0) and the second point is at coordinates (6, 6).
The variable "distance" is defined and assigned the value of the Euclidean distance between the two points.
The final distance is then printed using the print() function.
The final output will be 6.324555320336759 which is the distance between the two points (4,0) and (6,6).

## #41
Write a Python program to check whether a file exists.

In [ ]:
# Import the os.path module to work with file and directory paths
import os.path

# Check if 'main.txt' is a file and print the result.
print(os.path.isfile('main.txt'))

# Check if 'main.py' is a file and print the result
print(os.path.isfile('main.py'))

# Check if 'w3resource_python.ipynb' is a file and print the result
print(os.path.isfile('w3resource_python.ipynb'))

False
False
False


**Explanation:**

The said Python code imports the os.path module, which contains functions for interacting with the file system.

os.path.isfile('main.txt') checks whether a file named 'main.txt' exists in the current directory and returns True if it does and False if it does not.
os.path.isfile('main.py') checks whether a file named 'main.py' exists in the current directory and returns True if it does and False if it does not.
Then it prints the output of these two function calls.

In [ ]:
# Import the os.path module to work with file and directory paths.
import os.path

# Check if 'main.txt' exists (can be a file or directory) and print the result.
print(os.path.exists('main.txt'))

# Check if 'main.py' exists (can be a file or directory) and print the result.
print(os.path.exists('main.py'))

# Check if 'w3resource_python.ipynb' exists (can be a file or directory) and print the result.
print(os.path.exists('w3resource_python.ipynb'))

False
False
False


Explanation:
**bold text**
The said Python code imports the os.path module, which contains functions for interacting with the file system.

os.path.exists('main.txt') checks whether a file or directory named 'main.txt' exists in the current directory and returns True if it does and False if it does not.
os.path.exists('main.py') checks whether a file or directory named 'main.py' exists in the current directory and returns True if it does and False if it does not.
Then it prints the output of these two function calls.

The difference with previous example is that, os.path.exists() checks for the existence of file or directory, where as os.path.isfile() is used to check for the existence of file only.

In [ ]:
# Open the file 'main.py' for reading.
my_file = open('main.py')

try:
  # Close the file.
  my_file.close()
  # Print the "File found!" if the file was successfully closed
  print("File found!")
except FileNotFoundError:
  # Print "File not found!" if a FileNotFoundError occurs when closing the file.
  print("File not found!")

FileNotFoundError: [Errno 2] No such file or directory: 'main.py'

**Explanation:**

The said Python code opens a file named 'main.py' in the current working directory using the built-in open() function. The file object is then assigned to the variable "my_file".

After that, a try-except block is used to handle any errors encountered during the file closure process. If the file is successfully closed, the program will print "File found!" to the console.

If the file cannot be closed, a FileNotFoundError will be raised and the code in the except block will be executed. This will print "File not found!" to the console.

## #42
Write a Python program to determine if a Python shell is executing in 32bit or 64bit mode on OS.

In [ ]:
# Import the 'struct' modeule, which provides pack and unpack functions for working with variable-lenth binary data.
import struct

# Use the 'calcsize' function to determine the size (in bytes) of the C int type for the current platform.
# The format string "P" is used to represent the C void pointer type, and multiplying it by 8 gives the size in bits.
# The result will be 32 for 32-bit platforms and 64 for 64-bit platforms
print(struct.calcsize("P") * 8)

64


Explanation:
**bold text**
The said Python code imports the "struct" module, which converts between Python values and C structs represented as Python bytes objects.

The struct.calcsize() function is used to determine the size of a C data type, in bytes. In this case, the argument passed to the function is "P", which represents the C char * data type.

The value returned by struct.calcsize("P") is then multiplied by 8, which is used to convert the size from bytes to bits. This is because the size of a pointer is typically represented in bits, rather than bytes.

Finally, the result is printed to the console.

In [ ]:
# Import the 'platform' and 'struct' modules.
import platform
import struct

# Use the 'architecture' function from the 'platform' module to get the bit architecutre (32-bit or 64-bit) of the current platform.
# The [0] index retrieves the first element of the result, which is the architecture string
architecture = platform.architecture()[0]

# Print the bit architecture string, which will be "32bit" or "64bit"
print(architecture)

# Use the 'calcsize function from the 'struct' module to determine the size (in bytes) of the C int type for the current platform.
# The format string "p" is used to represent the C void pointer type, and multiplying it by 8 give the size in bits.
# The result will be 32 for 32-bit platforms and 64 for 64-bit platforms
print(struct.calcsize("P") * 8)

64bit
64


**Explanation:**

The said Python code imports two modules platform and struct.

The "platform" module provides an access to underlying platform’s identifying data. Specific platforms listed alphabetically, with Linux included in the Unix section.

The "platform.architecture()" function returns a tuple (bits, linkage) which contain information about the bit architecture and the linkage format used for the executable. Both values are returned as strings.

This "struct" module converts between Python values and C structs represented as Python bytes objects. The "struct.calcsize" returns the size of the struct (and hence of the bytes object produced by pack(format, ...)) corresponding to the format string format.

The struct.calcsize("P") function is used to determine the size of a C data type, in bytes. In this case, the argument passed to the function is "P", which represents the C char * data type.

The value returned by struct.calcsize("P") is then multiplied by 8, which is used to convert the size from bytes to bits. This is because the size of a pointer is typically represented in bits, rather than bytes.

Then both the values are printed to the console, first the architecture of the system and then the size of pointer in bits.

## #43
Write a Python program to get OS name, platform and release information.

os.name: The name of the operating system dependent module imported. The following names have currently been registered: 'posix', 'nt', 'java'.
platform.system(): Return the name of the OS system is running on
platform.release(): Return the version of the operating system

In [ ]:
# Import the 'platform' and 'os' modules.
import platform
import os

# Print the name of the operating system based on the 'os.name' attribute
# 'os.name' provides the name of the operating system dependent module imported.
print("Name of the operating system:", os.name)

# Print the name of the OS system using the 'platform.system()' function.
# 'platform.system()' returns the name of the operating system, such as 'Windows', 'Linux', or 'Darwin' (macOS).
print("\nName of the OS system:", platform.system())

# Print the version of the operating system using the 'platform.release()' function
# 'platform.release()' returns the version or release of the operating system
print("\nVersion of the operating system:", platform.release())

Name of the operating system: posix

Name of the OS system: Linux

Version of the operating system: 6.1.58+


**Explanation:**

This code imports two modules platform and os in Python.

os.name returns the operating system dependent module imported. The following names have currently been registered: 'posix', 'nt', 'java'.

platform.system() returns the system/OS name, such as 'Linux', 'Darwin', 'Java', 'Windows'. An empty string is returned if the value cannot be determined.

platform.release() returns the system’s release, e.g. '2.2.0' or 'NT'. An empty string is returned if the value cannot be determined.

The code prints the name of the operating system using os.name, the name of the OS system using platform.system() and version of the operating system using platform.release().

The name, version, and type of the operating system on which the code runs will be provided.

In [ ]:
import os
import sys
import platform
import sysconfig
print("os.name                  ", os.name)
print("sys.platform             ", sys.platform)
print("platform.system()        ", platform.system())
print("sysconfig.get_platform() ", sysconfig.get_platform())
print("platform.machine()       ", platform.machine())
print("platform.architecture()  ", platform.architecture())

os.name                   posix
sys.platform              linux
platform.system()         Linux
sysconfig.get_platform()  linux-x86_64
platform.machine()        x86_64
platform.architecture()   ('64bit', 'ELF')


## #44
Write a Python program to locate Python site packages

In [ ]:
# Import the 'site' module
import site

# Use the 'site.getsitepackages()' function to retrieve site packages' paths.
# 'site.getsitepackages()' returns a list of paths where site packages are installed
print(site.getsitepackages())

['/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages']


Explanation:

The above Python code imports the ‘site’ module and then calls the getsitepackages() function.

By calling print(site.getsitepackages()), the code will print a list of these paths to the console output. This can be useful for understanding where Python packages are installed on a particular system, which can be important for managing dependencies in Python projects.

## #45
Write a Python program that calls an external command

In [ ]:
# Import the 'call' function from the 'subprocess' module.
from subprocess import call

# Use the 'call' function to execute the "ls -l" command
# This command lists the files and directories in the current directory with details
call(["ls", "-l"])

0

**Explanation:**

In Python The subprocess module allows us to spawn new processes, connect to their input/output/error pipes, and obtain their return codes. This module intends to replace several older modules and functions:

The above Python code uses the ‘subprocess’ module to execute a command in the shell. Then, it calls the call function from the subprocess module with a list of arguments as its parameter.

When the call function is executed, it will execute the specified command in the shell and wait for it to complete before returning.

So, when the above code is executed, it will print the long format list of files in the current directory on the console output, just like running the ls -l command directly in the terminal.

In [ ]:
# Import the 'os' module to work with the operating system
import os

# Use 'os.system(command)' to execute the 'ls -l' command in the system's shell
# This command lists the files and directories in the current directory and prints the result
print(os.system('ls -l'))

0


Explanation:

The ‘OS’ module provides a portable way of using operating system dependent functionality.

The above Python code imports the os module and then calls its system function to execute a shell command.

When the system function is called, it executes the specified command in the shell. In this case, the command is ls -l, which is executed in the shell.

Finally, the code calls print() function to output the return value of the system function.

In [ ]:
# Import the 'psutil' module for system monitoring, including CPU information
import psutil

# Use 'psutil.cpu_count()' to get the number of available CPU cores
# THis function returns the number of logical CPU cores in the system
print(psutil.cpu_count())

2


**Explanation:**

psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python. It is useful mainly for system monitoring, profiling and limiting process resources and management of running processes.

In the above Python code we first import the ‘psutil’ module and then calls its cpu_count() function to get the number of CPU cores on the current system.

When the cpu_count() function is called, it returns the number of CPU cores on the system. Finally the code calls print() function to output the number of CPU cores on the system to the console output.

## #46
Write a Python program to retrieve the path and name of the file currently being executed

In [ ]:
# Import the 'os' module to work with the operating system.
import os

# Use the 'os.path.realpath(__file__)' to get the full path of the current Python script.
# This will print the path of the current file.
print("Current File Name: ", os.path.realpath(__file__))

NameError: name '__file__' is not defined

**Explanation:**

The ‘OS’ module provides a portable way of using operating system dependent functionality. The realpath() function returns the canonical path of the specified filename, eliminating any symbolic links encountered in the path (if they are supported by the operating system).

If a path doesn’t exist or a symlink loop is encountered, and strict is True, OSError is raised. If strict is False, the path is resolved as far as possible and any remainder is appended without checking whether it exists.

The above Python code imports the ‘os’ module and then calls its path sub-module's realpath function to get the full path of the current script file. The code then uses the print function to output the string "Current File Name : " followed by the full path of the script file to the console output.

## #47
Write a Python program to find out the number of CPUs used

In [ ]:
# Import the 'multiprocessing' module to work with multi-processing features
import multiprocessing

# Use 'multiprocessing.cpu_count()' to determine the number of available CPU cores
cpu_count = multiprocessing.cpu_count()

# Print the number of CPU cores available on the system
print(cpu_count)

2


Explanation:
**bold text**
multiprocessing is a package that supports spawning processes using an API similar to the threading module. The multiprocessing package offers both local and remote concurrency, effectively side-stepping the Global Interpreter Lock by using subprocesses instead of threads. Due to this, the multiprocessing module allows the programmer to fully leverage multiple processors on a given machine. It runs on both Unix and Windows.

cpu_count() function returns the number of CPUs in the system.

The above Python code imports the multiprocessing module and then calls its cpu_count() function to get the number of CPU cores on the current system. The code then calls print() function to print the number of CPU cores on the system to the console output.

In [ ]:
# Improt the 'os' module to access system-related functions
import os

# Use 'os.cpu_count()' to determine the number of available CPU cores
cpu_count = os.cpu_count()

# Print the number of CPU cores available on the system
print(cpu_count)

2


**Explanation:**

The 'OS' module provides a portable way of using operating system dependent functionality. cpu_count() function returns the number of CPUs in the system. Returns None if undetermined.

The above Python code imports the multiprocessing module and then calls its cpu_count() function to get the number of CPU cores on the current system.

When the cpu_count() function is called, it returns the number of CPU cores on the system. The code then calls print() function to output the number of CPU cores on the system to the console output.

## #48
Write a Python program to parse a string to float or integer

In [ ]:
# Define a string 'n' containing a numeric value.
n = "246.2458"

# Convert the string 'n' to a floating-point number and print the result.
print(float(n))

# Convert the floating-point number to an integer, truncating any decimal part, and print the result.
print(int(float(n)))

246.2458
246


**Explanation:**

float(x=0.0) : Returns a floating point number constructed from a number or string x.

If the argument is a string, it should contain a decimal number, optionally preceded by a sign, and optionally embedded in whitespace. The optional sign may be '+' or '-'; a '+' sign has no effect on the value produced. The argument may also be a string representing a NaN (not-a-number), or positive or negative infinity.

The above Python code creates a variable n with the value "246.2458" as a string. The float() function is used to convert the string "246.2458" to a floating-point number. The print() function is then used to output this floating-point number to the console.

In [ ]:
# Define a function 'test' that takes a string 's' as input.
def test(s):
  try:
    # Try to convert the input string to an integer
    return int(s)
  except ValueError:
    # If the conversion to an integer raises a ValueError (i.e., it's not an integer),
    # then try to convert the string to a floating-point number (float)
    return float(s)

# Call the 'test' function with different input values and print the results
print(test('12'))       # Try to convert '12' to an integer
print(test('233.12'))   # Try to convert '233.12' to a float

12
233.12


## #49
Write a Python program to list all files in a directory

In [ ]:
# Import necessary functions and modules from the 'os' library
from os import listdir
from os.path import isfile, join

# Create a list 'files_list' that contains the names of files in the '/home/students' directory.
# It uses a list comprehension to filter files using 'isfile' and 'join' functions
files_list = [f for f in listdir('/home/students') if isfile(join('/home/students', f))]

# Print the list of file names
print(files_list)

FileNotFoundError: [Errno 2] No such file or directory: '/home/students'

**Explanation:**

The ‘OS’ module provides a portable way of using operating system dependent functionality.

os.listdir(path='.'): Return a list containing the names of the entries in the directory given by path. The list is in arbitrary order, and does not include the special entries '.' and '..' even if they are present in the directory.

os.path.isfile(path): Return True if path is an existing regular file. This follows symbolic links, so both islink() and isfile() can be true for the same path.

os.path.join(path, *paths): Join one or more path segments intelligently. The return value is the concatenation of path and all members of *paths, with exactly one directory separator following each non-empty part, except the last.

The above Python code imports the ‘listdir’ and ‘isfile’ functions from the os module, and the ‘join’ function from the os.path module. It then uses the above three functions to generate a list of all the files in the directory /home/students. Finally print() function prints the resulting list of files.

## #50
Write a Python program to print without a newline or space

In [ ]:
# Iterate through a range of numbers from 0 to 9 (inclusive)
for i in range(0, 10):
  # Print an asterisk '*' character on the same line using the 'end' parameter
  print('*', end="")
# Print a newline character to move to the next line
print("\n")

**********



**Explanation:**

In the above Python code the for loop iterates through the range of numbers from 0 to 9 (inclusive) generated by the range() function. On each iteration, it prints a single asterisk character using the print() function, with the end parameter set to an empty string (""). This causes the print() function not to insert a newline character after each asterisk.

After the loop completes, a newline character is printed to the console using the print() function.

In [ ]:
# Import the functools module to use the 'partial' function
import functools

# Create a partial function 'printf' based on the 'print' function with 'end' parameter set to an empty string
printf = functools.partial(print, end="")

# Iterate through a range of numbers from 0 to 9 (inclusive)
for i in range(0, 10):
  # Use the 'printf' function to print an asterisk '*' character to the same line
  printf('*')

  # Note: The variable 'i' is defined but not used in this code

**********

**Explanation:**

The functools module is for higher-order functions: functions that act on or return other functions. In general, any callable object can be treated as a function for the purposes of this module.

functools.partial: Return a new partial object which when called will behave like func called with the positional arguments args and keyword arguments keywords.

In the above Python code we use the ‘functools’ module to create a partial function that prints a string without a newline character.

After defining the printf function, a for loop is used to iterate through the range of numbers from 0 to 9 (inclusive) generated by the range() function. On each iteration, it calls the printf() function to print a single asterisk character to the console without adding a newline character.

## #51
Write a Python program to determine the profiling of Python programs

In [ ]:
# Import the cProfile module, which provides a way to profile Python code
import cProfile
# Define a function names 'sum'
def sum():
  # Print the result of adding 1 and 2 to the console
  print(1 + 2)
# Use cProfile to profile the 'sum' function
cProfile.run('sum()')

3
         39 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-7-0bd80fa01747>:4(sum)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        3    0.000    0.000    0.000    0.000 iostream.py:195(schedule)
        2    0.000    0.000    0.000    0.000 iostream.py:308(_is_master_process)
        2    0.000    0.000    0.000    0.000 iostream.py:321(_schedule_flush)
        2    0.000    0.000    0.000    0.000 iostream.py:384(write)
        3    0.000    0.000    0.000    0.000 iostream.py:91(_event_pipe)
        3    0.000    0.000    0.000    0.000 socket.py:543(send)
        3    0.000    0.000    0.000    0.000 threading.py:1102(_wait_for_tstate_lock)
        3    0.000    0.000    0.000    0.000 threading.py:1169(is_alive)
        3    0.000    0.000    0.000    0.000 threading.py:553(is_set)
        1    0.000    0.00

**Explanation:**

cProfile provide deterministic profiling of Python programs. A profile is a set of statistics that describes how often and for how long various parts of the program executed.profile.run(command, filename=None, sort=- 1): This function takes a single argument that can be passed to the exec() function, and an optional file name.

The above Python code imports the cProfile module. The sum() function defined in the code adds the numbers 1 and 2 and prints the result to the console using the print() function.

The cProfile.run() function is used to profile the execution of the sum() function. The run() function takes a string as its parameter that represents the code to be executed and profiled. In this case, it is passed the function call sum() as a string.

## #52
Write a Python program to print to STDERR

In [ ]:
# Import the 'print_function' feature from the '__future__' module to enable Python 3-style print function
from __future__ import print_function

# Import the 'sys' module, which provides access to some variables used or maintained by the interpreter
import sys

# Define a custom 'eprint' function that prints to the standard error stream
def eprint(*args, **kwargs):
  # Call the 'print' function with the provided argument and keyword arguments
  # Use 'file=sys.stderr' to print to the standard error stream (stderr)
  print(*args, file=sys.stderr, **kwargs)

# Call the 'eprint' function with the specified arguments and separator
eprint("abd", "efg", "xyz", sep="--")

abd--efg--xyz


**Explanation:**

__future__ is a real module, and serves three purposes:

To avoid confusing existing tools that analyze import statements and expect to find the modules they’re importing.
To ensure that future statements run under releases prior to 2.1 at least yield runtime exceptions (the import of __future__ will fail, because there was no module of that name prior to 2.1).
To document when incompatible changes were introduced, and when they will be — or were — made mandatory. This is a form of executable documentation, and can be inspected programmatically via importing __future__ and examining its contents.
Sys module - This module provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter. It is always available.

In the above Python exercise the eprint() function takes any number of arguments and prints them to the standard error stream (stderr) using the print() function. The file parameter is set to sys.stderr, which redirects the output to the standard error stream instead of the standard output stream.

Finally, the eprint() function is called with the arguments "abc", "efg", and "xyz", separated by the string "--". This causes the string "abc--efg--xyz" to be printed to the standard error stream.

## #53
Write a Python program to access environment variables

In [ ]:
# Import the 'os' module to access operating system-related functionality, inclueding environment variables
import os

# Print a separator for clarity
print('*----------------------------------*')

# Print all environment variables
print(os.environ)

# Print a separator for clarity
print('*----------------------------------*')

# Access and print the 'HOME' environment variable
print(os.environ['HOME'])

# Print a separator for clarity
print('*----------------------------------*')

# Access and print the 'PATH' environment variable
print(os.environ['PATH'])

# Print a separator for clarity
print('*----------------------------------*')

*----------------------------------*
environ({'SHELL': '/bin/bash', 'NV_LIBCUBLAS_VERSION': '12.2.5.6-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'COLAB_JUPYTER_TRANSPORT': 'ipc', 'NV_NVML_DEV_VERSION': '12.2.140-1', 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8', 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events', 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.19.3-1+cuda12.2', 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.19.3-1', 'VM_GCE_METADATA_HOST': '169.254.169.253', 'HOSTNAME': 'c682fdb1799a', 'LANGUAGE': 'en_US', 'TBE_RUNTIME_ADDR': '172.28.0.1:8011', 'COLAB_TPU_1VM': '', 'GCE_METADATA_TIMEOUT': '3', 'NVIDIA_REQUIRE_CUDA': 'cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,dri

**Explanation:**

The ‘OS’ module provides a portable way of using operating system dependent functionality.

In the above exercise we imports the os module and uses it to print environment variables to the console output.

The environ attribute of the os module is a dictionary-like object that represents the environment variables in the current process. The print() function is used to print the entire dictionary of environment variables to the console using os.environ.

The code then uses square brackets ([]) to access specific environment variables by their names. In this case, it prints the values of the HOME and PATH environment variables to the console using os.environ['HOME'] and os.environ['PATH'], respectively.

In [ ]:
# Import the 'os' module to access operating system-related functionality, including environment variables
import os

# Iterate through all environment variables in the 'os.environ' dictionary
for data in os.environ:
  # Print the name of the environment variable
  print(data)
  # Print a separator for clarity
  print('-' * 15)
  # Print the value of the environment variable
  print(os.environ[data])
  # Print a line of '=' characters as an additional separator
  print('=' * 30)

SHELL
---------------
/bin/bash
NV_LIBCUBLAS_VERSION
---------------
12.2.5.6-1
NVIDIA_VISIBLE_DEVICES
---------------
all
COLAB_JUPYTER_TRANSPORT
---------------
ipc
NV_NVML_DEV_VERSION
---------------
12.2.140-1
NV_CUDNN_PACKAGE_NAME
---------------
libcudnn8
CGROUP_MEMORY_EVENTS
---------------
/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events
NV_LIBNCCL_DEV_PACKAGE
---------------
libnccl-dev=2.19.3-1+cuda12.2
NV_LIBNCCL_DEV_PACKAGE_VERSION
---------------
2.19.3-1
VM_GCE_METADATA_HOST
---------------
169.254.169.253
HOSTNAME
---------------
c682fdb1799a
LANGUAGE
---------------
en_US
TBE_RUNTIME_ADDR
---------------
172.28.0.1:8011
COLAB_TPU_1VM
---------------

GCE_METADATA_TIMEOUT
---------------
3
NVIDIA_REQUIRE_CUDA
---------------
cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=4

## #54
Write a Python program to get the current username

In [ ]:
# Import the 'getpass' module to access user-related functionality, including getting the current username
import getpass

# Get the 'getuser()' function from the 'getpass' module to retrieve the current username
# Then, print the username to the console
print(getpass.getuser())

root


**Explanation:**

The above Python code imports the ‘getpass’ module and uses it to print the username of the current user to the console output.

The ‘getpass’ module provides a way to get the username of the current user, as well as prompt the user to enter a password without echoing the input to the console.

getpass.getuser() - This function checks the environment variables LOGNAME, USER, LNAME and USERNAME, in order, and returns the value of the first one which is set to a non-empty string. If none are set, the login name from the password database is returned on systems which support the pwd module, otherwise, an exception is raised.

The output of the code will be the username of the current user, which is retrieved from the operating system.

In [ ]:
# Import the 'os' and 'pwd' modules to access operating system and user-related functionality
import os
import pwd

# Define a function 'get_username' to retrieve the username of the current user
def get_username():
  # Use 'os.getid()' to get the user ID of the current user, and then pass it to 'pwd.getpwuid' to get the user informaiton
  # The '[0]' index extracts the username from the user information
  return pwd.getpwuid(os.getuid())[0]

# Call the 'get_username' function and print the result to the console
print(get_username())

root


**Explanation:**

The ‘OS’ module provides a portable way of using operating system dependent functionality.

This ‘pwd’ module provides access to the Unix user account and password database. It is available on all Unix versions.

The get_username() function defined in the code uses the os.getuid() function to get the user ID of the current process, and then passes this ID to the pwd.getpwuid() function to get a pwd.struct_passwd object representing the user account information.

The username of the user is obtained from the pwd.struct_passwd object using its pw_name attribute. The get_username() function returns this username as a string.

Finally, the print() function prints the username returned by get_username() to the console.

## #55
Write a Python program to find local IP addresses using Python's stdlib

In [ ]:
# Import the 'socket' module to work with network-related functions
import socket

# The following code retrieves the local IP address of the current machine:
# 1. Use 'socket.gethostname()' to get the local hostname
# 2. Use 'socket.gethostbyname_ex()' to get a list of IP addresses associated with the hostname
# 3. Filter the list to exclude any IP addresses starting with "127." (loopback addresses)
# 4. Extract the first IP address (if available) from the filtered list
# 5. Print the obtained IP address to the console

# Step 1: Get the local hostname
local_hostname = socket.gethostname()

# Step 2: Get a list of IP addresses associated with the hostname
ip_addresses = socket.gethostbyname_ex(local_hostname)[2]

# Step 3: Filter out loopback addresses (IPs starting with "127.")
filtered_ips = [ip for ip in ip_addresses if not ip.startswith("127.")]

# Step 4: Extract the first IP address (if available) from the filtered list
first_ip = filtered_ips[:1]

# Step 5: Print the obtained IP address to the console
print(first_ip[0])

172.28.0.12


**Explanation:**

What is socket module in Python?

On top of the operating system, the socket module defines how servers and clients communicate at hardware level. In addition to supporting connection-oriented protocols, the socket API also supports connectionless protocols. It is available on all modern Unix systems, Windows, MacOS, and probably additional platforms.

socket.gethostbyname_ex(hostname) - Translate a host name to IPv4 address format, extended interface. Return a triple (hostname, aliaslist, ipaddrlist) where hostname is the host’s primary host name.

socket.gethostname() - Return a string containing the hostname of the machine where the Python interpreter is currently executing.

socket.socket(family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None) - Create a new socket using the given address family, socket type and protocol number.

The above Python code first imports the socket module.

The code uses a list comprehension to extract the IP address of the current machine from the output of the socket.gethostbyname_ex() function.

The innermost list comprehension filters out any IP addresses that start with 127. (which are reserved for loopback testing) and selects the first IP address in the resulting list. This is done using the if statement and the [:1] slice notation.

The outer list comprehension combines the list of IP addresses obtained from the previous step with a list that contains the IP address of Google's DNS server (8.8.8.8). This is done using nested lists and a list comprehension that creates a UDP socket and queries the server for its IP address.

Finally, the print() function is used to print the IP address of the current machine.

## #56
Write a Python program to get the height and width of the console window

In [ ]:
# Import necessary modules for working with the terminal size
import fcntl
import termios
import struct

# Define a function named 'terminal_size' to retrieve the terminal size
def terminal_size():
  # Use 'fcntl' and 'termios' to fetch terminal-related information, including size
  # This code queries the terminal's width (columns) and height (rows)
  # It uses the 'TIOCGWINSZ' ioctl command to get window size information

  # 1. Open file descriptor 0 (stdin)
  # 2. Call 'fcntl.ioctl' with 'TIOCGWINSZ' to fetch window size information
  # 3. Unpack the received information into 'th' (height), 'tw' (width), 'hp' (horizontal pixel size), and 'wp' (vertical pixel size)
  th, tw, hp, wp = struct.unpack('HHHH', fcntl.ioctl(0, termios.TIOCGWINSZ, struct.pack('HHHH', 0, 0, 0, 0)))

  # Return the terminal width and height
  return tw, th

# Call the 'terminal_size' function to get the terminal size and print the result
print('Number of columns and rows: ', terminal_size())

OSError: [Errno 25] Inappropriate ioctl for device

**Explanation**:

The above Python code defines a function terminal_size() that uses system calls to get the size of the terminal window in columns and rows. It then calls the terminal_size() function and prints the result to the console output.

Then the code imports fcntl, termios, and struct modules.

fcntl - This module performs file control and I/O control on file descriptors. It is an interface to the fcntl() and ioctl() Unix routines.

termios - This module provides an interface to the POSIX calls for tty I/O control. For a complete description of these calls, see termios(3) Unix manual page.

struct - This module converts between Python values and C structs represented as Python bytes objects. Compact format strings describe the intended conversions to/from Python values.

The terminal_size() function uses the fcntl.ioctl() function to query the size of the terminal window using the termios.TIOCGWINSZ ioctl call. This call returns a struct.pack() object containing four integers representing the number of rows and columns of the terminal, as well as the horizontal and vertical pixel size.

The struct.unpack() function is used to unpack the four integers from the struct.pack() object into separate variables th, tw, hp, and wp. The function then returns the values of tw (the width of the terminal window in columns) and th (the height of the terminal window in rows) as a tuple.

Finally, the print() function is used to print the size of the terminal window to the console.

## #57
Write a Python program to get the execution time of a Python method

In [ ]:
# Import the 'time' module to work with time-ralted functions
import time

# Define a function named 'sum_of_n_numbers' that calculates the sum of the first 'n' natural numbers
def sum_of_n_numbers(n):
  # Record the current time before the calculation
  start_time = time.time()

  # Initialize a variable 's' to store the sum
  s = 0

  # Loop through numbers from 1 to 'n' and accumulate the sum
  for i in range(1, n + 1):
    s = s + i

  # Record the current time after the calculation
  end_time = time.time()

  # Return both the calculated sum and the time taken for the calculation
  return s, end_time - start_time

# Define the value of 'n' as 5
n = 5

# Print the result, including the time taken to calculate the sum
print("\nTime to sum of 1 to", n, "and required time to calculate is:", sum_of_n_numbers(n))


Time to sum of 1 to 5 and required time to calculate is: (15, 2.384185791015625e-06)


**Explanation:**

The above Python code defines a function sum_of_n_numbers() that calculates the sum of the first n positive integers, and returns the sum and the time it took to calculate the sum.

time module - This module provides various time-related functions.

The sum_of_n_numbers() function uses a for loop to add up the first n positive integers and calculates the time it takes to do so using the time.time() function to get the start and end times of the operation. The function returns a tuple containing the sum of the first n positive integers and the time taken to calculate the sum.

Finally the code then calls the sum_of_n_numbers() function with an argument of n=5, and prints the result to the console using the print() function. The output displays the time it took to calculate the sum of the first 5 positive integers and the calculated sum.

## #58
Write a Python program to sum the first n positive integers

In [ ]:
# Prompt the user for input and convert it to an integer
n = int(input("Input a number: "))

# Calculate the sum of the first 'n' positive integers using the formula
sum_num = (n * (n + 1)) / 2

# Print the result, indicating the sum of the first 'n' positive integers
print("Sum of the first", n, "positive integers:", sum_num)

Input a number: 64
Sum of the first 64 positive integers: 2080.0


**Explanation:**

The input() function is used to prompt the user to input a number, and the int() function is used to convert the input to an integer value, which is stored in the variable n.

The sum of the first n positive integers is calculated using the formula sum_num = (n * (n + 1)) / 2, which is the sum of an arithmetic sequence with a first term of 1, a common difference of 1, and a total of n terms.

Finally, the print() function is used to output a message to the console in the format "Sum of the first n positive integers: sum_num", where n is the user input and sum_num is the calculated sum.

In [ ]:
# Prompt the user for input and convert it to an integer.
n = int(input("Input an integer: "))

# Calculate the sum of the first 'n' positive integers using the built-in 'sum' function and 'range'.
result = sum(range(n+1))

# Print the result, indicating the sum of the first 'n' positive integers.
print("Sum of the first", n, "positive integers:", result)

Input an integer: 4


TypeError: sum() takes 0 positional arguments but 1 was given

**Explanation:**

In the above code -

n = int(input("Input a number: ")): Here the input() function is used to prompt the user to enter an integer, and the int() function is used to convert the input to an integer value, which is stored in the variable n.

sum_num = (n * (n + 1)) / 2: The range() function is then used to generate a sequence of integers from 0 to n inclusive, which is passed as an argument to the sum() function. The sum() function calculates the sum of the sequence and stores the result in the variable result.

print("Sum of the first", n ,"positive integers:", sum_num): Finally, the print() function is used to output a message to the console in the format "Sum of the first n positive integers: result", where n is the user input and result is the calculated sum.

## #59
Write a Python program to convert height (in feet and inches) to centimeters

In [ ]:
# Prompt the user to input their height
print("Input your height: ")

# Read the feet part of the height and convert it to an integer
h_ft = int(input("Feet: "))

# Read the inches part of the height and conver it to an integer
h_inch = int(input("Inches: "))

# Convert the height from feet and inches to inches
h_inch += h_ft * 12

# Calculate the height in centimeters by multiplying by the conversion factor (2.54)
h_cm = round(h_inch * 2.54, 1)

# Print the calculated height in centimeters
print("Your height is: %d cm." %h_cm)

Input your height: 
Feet: 5
Inches: 2
Your height is: 157 cm.


**Explanation:**

h_ft = int(input("Feet: "))
h_inch = int(input("Inches: "))
In the above code -

The input() function is used to prompt the user to enter their height in feet and inches, and the int() function is used to convert the input to integer values for h_ft (height in feet) and h_inch (height in inches).

h_inch += h_ft * 12: The height in inches is then calculated by adding h_ft * 12 to h_inch, which converts the height to inches.

h_cm = round(h_inch * 2.54, 1): The height in centimeters is calculated by multiplying the height in inches by 2.54 (the conversion factor from inches to centimeters), and rounding the result to one decimal place using the round() function.

Finally, the print() function prints a message to the console in the format "Your height is : height_cm cm".

## #60
Write a Python program to calculate the hypotenuse of a right angled triangle

In [ ]:
# Import the sqrt function from the math module to calculate the square root
from math import sqrt

# Prompt the user to input the length of the shorter triangle sides
print("Input lengths of shorter triangle sides:")

# Read and convert the input for side 'a' to a floating-point number
a = float(input("a: "))

# Read and convert the input for side 'b' to a floating-point number
b = float(input("b: "))

# Calculate the length of the hypotenuse using the Pythagorean theorem
c = sqrt(a**2 + b**2)

# Print the calculated length of the hypotenuse
print("The length of the hypotenuse is:", c)

Input lengths of shorter triangle sides:
a: 10
b: 15
The length of the hypotenuse is: 18.027756377319946


**Explanation:**

from math import sqrt: The sqrt() function is imported from the math module to allow the calculation of the square root of a value.

a = float(input("a: "))
b = float(input("b: "))
In the above code -

The input() function is used to prompt the user to enter the lengths of the shorter sides of a right triangle, and the float() function is used to convert the input to floating-point values, which are stored in the variables a and b.

c = sqrt(a**2 + b**2): The length of the hypotenuse is then calculated using the Pythagorean theorem, which states that the square of the length of the hypotenuse (c) is equal to the sum of the squares of the lengths of the other two sides (a and b). The square root of this sum is taken using the sqrt() function, and the result is stored in the variable c.

Finally, the print() function prints a message to the console in the format "The length of the hypotenuse is: c", where c is the calculated length of the hypotenuse.

In [ ]:
# Define a function named 'test' that takes two parameters 'x' and 'y'
def test(x, y):
  # Calculate the length of the hypotenuse (h) using the Pythagorean theorem
  h = (x**2 + y**2)**0.5

  # Return the calculated hypotenuse
  return h

# Call the 'test' function with different values and print the results
print(test(3, 4))     # Calculate the hypotenuse for a right triangle with sides 3 and 4
print(test(3.5, 4.4)) # Calculate the hypotenuse for a right triangle with sides 3.5 and 4.4

5.0
5.622277118748239


**Explanation:**

In the above code -

The test() function takes two arguments, x and y, which represent the lengths of the legs of a right triangle. The length of the hypotenuse is calculated using the Pythagorean theorem, which states that the square of the length of the hypotenuse (h) is equal to the sum of the squares of the lengths of the other two sides (x and y). The square root of this sum is taken using the exponentiation operator (**) with a value of 0.5, and the result is stored in the variable h. The function returns the value of h.

The code then calls the test() function with two sets of arguments, (3, 4) and (3.5, 4.4), and prints the results to the console using the print() function.

## #61
Write a Python program to convert the distance (in feet) to inches, yards, and miles

In [ ]:
# Prompt the user to input a distance in feet and store it in the variable 'd_ft'
d_ft = int(input("Input distance in feet: "))

# Convert the distance in feet to inches and store it in the variable 'd_inches'
d_inches = d_ft * 12

# Convert the distance in feet to yards and store it in the variable 'd_yards'
d_yards = d_ft / 3.0

# Convert the distance in feet to miles and store it in the variable 'd_miles'
d_miles = d_ft / 5280.0

# Print the calculated distance in inches, yards, and miles
print("The distance in inches is %i inches." % d_inches)
print("The distance in yards is %.2f yards." % d_yards)
print("The distance in miles is %.2f miles." % d_miles)

Input distance in feet: 500
The distance in inches is 6000 inches.
The distance in yards is 166.67 yards.
The distance in miles is 0.09 miles.


## #62
Write a Python program to convert all units of time into seconds

In [ ]:
# Prompt the user to input a number of days and store it in the variable 'days'
days = int(input("Input days: ")) * 3600 * 24
# Prompt the user to input a number of hours and store it in the variable 'hours'
hours = int(input("Input hours: ")) * 3600
# Prompt the user to input a number of minues and store it in the variable 'minutes'
minutes = int(input("Input minutes: ")) * 60
# Prompt the user to input the number of seconds and store it in the variable 'seconds'
seconds = int(input("Input seconds: "))
# Calculate the total time in seconds by adding the converted values
time = days + hours + minutes + seconds
# Print the total time in seconds
print("The amount of seconds:", time)

Input days: 3
Input hours: 10
Input minutes: 24
Input seconds: 40
The amount of seconds:  296680


## #63
Write a Python program to get an absolute file path

In [ ]:
# Define a function named absolute_file_path that takes a parameter 'path_fname'
def absolute_file_path(path_fname):
  # Import the 'os' module for working with file paths and directories
  import os

  # Use 'os.path.abspath()' to get the absolute file path by providing 'path_fname'
  return os.path.abspath(path_fname)

# Call the function and print the result, passing "test.txt" as the argument
print("Absolute file path: ", absolute_file_path("Test.txt"))

Absolute file path:  /content/Test.txt


In [ ]:
# Import the 'Path' class from the 'pathlib' module, which provides an object-oriented interface to file system paths
from pathlib import Path

# Create a Path object 'p' by providing the file path "main.py" and resolving it to its absolute path
p = Path("main.py").resolve()

# Print the absolute path of the file
print(p)

/content/main.py


## #64
Write a Python program that retrieves the data and time of file creation and modification

In [ ]:
# Import the 'os.path' and 'time' modules to work with file system paths and timestamps
import os.path, time

# Print the last modified timestamp of the file "test.txt" in a human-readable format
print("Last modified: %s" % time.ctime(os.path.getmtime("test.txt")))

# Print the creation timestamp of the file "test.txt" in a human-readable format
print("created: %s" % time.ctime(os.path.getctime("test.txt")))

## #65
Write a Python program that converts seconds into days, hours, minutes, and seconds

In [ ]:
# Prompt the user to input a time duration in seconds and convert it to a float
time = float(input("Input time in seconds: "))

# Calculate the number of full days in the given time duration
day = time // (24 * 3600)
# Update the time variable to hold the remaining seconds after substracting full days
time = time % (24 * 3600)

# Calculate the number of full hours in the remaining time
hour = time // 3600
# Update the time variable to hold the remaining seconds after subtracting full hours
time %= 3600

# Calculate the number of full minutes in the remaining time
minutes = time // 60
# Update the time variable to hold the remaining seconds after subtracting full minutes
time %= 60

# The 'time' variable now represents the remaining seconds, which is the number of seconds
seconds = time

# Print the time duration in the format "d:h:m:s"
print("d:h:m:s -> %d:%d:%d:%d" % (day, hour, minutes, seconds))

Input time in seconds: 6135218
d:h:m:s -> 71:0:13:38


## #66
Write a Python program to calculate the body mass index

In [ ]:
# Prompt the user to input their height in feet and convert it to a floating-point number
height = float(input("Input your height in feet: "))

# Prompt the user to input their weight in kilograms and convert it to a floating-point number
weight = float(input("Input your weight in kilograms: "))

# Calculate the body mass index (BMI) using the provided height and weight and round it to 2 decimal places
bmi = weight / (height * height)
rounded_bmi = round(bmi, 2)

# Print the calculated BMI
print("Your body mass index is: ", rounded_bmi)

Input your height in feet: 5
Input your weight in kilograms: 150
Your body mass index is:  6.0


In [ ]:
# Prompt the user to input their height in inches and convert it to a floating-point number
height = float(input("Input your height in inches: "))

# Prompt the user to input their weight in pounds and convert it to a floating-point number
weight = float(input("Input your weight in pounds: "))

# Calculate the body mass index (BMI) using the provided height and weight and round it to 2 decimal places
bmi = weight / ((height * height) * 703.0)
rounded_bmi = round(bmi, 2)

# Print the calculated BMI
print("Your body mass index is: ", rounded_bmi)

Input your height in inches: 62
Input your weight in pounds: 200
Your body mass index is:  0.0


## #67
Write a Python program to convert pressure in kilopascals to pounds per square inch, a millimeter of mercury (mmHg) and atmosphere pressure

In [ ]:
# Prompt the user to input pressure in kilopascals and convert it to a floating-point number
kpa = float(input("Input pressure in kilopascals: "))

# Convert kilopascals to pounds per square inch (psi) using the conversion factor
psi = kpa / 6.89475729

# Convert kilopascals to millimeters of mercury (mmHg) using the conversion factor
mmhg = kpa * 760 / 101.325

# Convert kilopascals to atmospheres (atm) using the conversion factor
atm = kpa / 101.325

# Print the pressure in pounds per square inch (psi) with 2 decimal places
print("The pressure in pounds per square inch: %.2f psi" % (psi))

# Print the pressure in millimeters of mercury (mmHg) with 2 decimal places
print("The pressure in millimeters of mercury: %.2f mmHg" % (mmhg))

# Print the atmosphere pressure (atm) with 2 decimal places
print("Atmosphere presure: %.2f atm." % (atm))

Input pressure in kilopascals: 15.86
The pressure in pounds per square inch: 2.30 psi
The pressure in millimeters of mercury: 118.96 mmHg
Atmosphere presure: 0.16 atm.


## #68
Write a Python program to calculate sum of digits of a number

In [ ]:
# Prompt the user to input a four-digit number and convert it to an integer
num = int(input("Input a four-digit number: "))

# Extract the thousands digit (x)
x = num // 1000

# Extract the hundreds digit (x1) by subtracting the thousands digit from the number
x1 = (num - x * 1000) // 100

# Extract the tens digit (x2) by subtracting the thousands and hundreds digits from the number
x2 = (num - x * 1000 - x1 * 100) // 10

# Extract the ones digit (x3) by subtracting the thousands, hundreds, and tens digits from the number
x3 = num - x * 1000 - x1 * 100 - x2 * 10

# Calculate the sum of the digits in the number and print the result
print("The sum of digits in the number is", x + x1 + x2 + x3)

Input a four-digit number: 8624
The sum of digits in the number is 20


## #69
Write a Python program to sort three integers without using conditional statements and loops

In [ ]:
# Prompt the user to input three integers and convert them to variables x, y, and z.
x = int(input("Input first number: "))
y = int(input("Input second number: "))
z = int(input("Input third number: "))

# Find the minimum value among x, y, and z and store it in variable a1
a1 = min(x, y, z)

# Find the maximum value among x, y, and z and store it in variable a3
a3 = max(x, y, z)

# Calculate the middle value (not the minimum or maximum) by subtracting a1 and a3 from the sum of x, y, and z
a2 = (x + y + z) - a1 -a3

# Print the numbers in sorted order (a1, a2, a3)
print("Numbers in sorted order: ", a1, a2, a3)

Input first number: 65
Input second number: 84
Input third number: 2
Numbers in sorted order:  2 65 84


## #70
Write a Python program to sort files by date

In [ ]:
# Import the necessary libraries to work with file operations and globbing
import glob
import os

# Use the glob module to find all files in the current directory with a ".txt" extension
files = glob.glob("*.txt")

# Sort the list of file names based on the modification time (getmtime) of each file
files.sort(key=os.path.getmtime)

# Print the sorted list of file names, one per line
print("\n".join(files))

In [ ]:
# Import the 'os' module for interacting with the operating system
import os

# Change the current working directory to 'D:'
os.chdir('D:')

# List files in the current directory, filter for regular files (not directories)
file_list = filter(os.path.isfile, os.listdir('.'))

# Sort the list of files based on their modification time
sorted_files = sorted(file_list, key=os.path.getmtime)

# Print the sorted list of file names, one per line
print('\n'.join(map(str, sorted_files)))

FileNotFoundError: [Errno 2] No such file or directory: 'D:'

## #71
Write a Python program to get a directory listing, sorted by creation date

In [ ]:
# Import necessary modules: 'stat' for file status, 'os' for operating system interactions,
# 'sys for command-line arguments, and 'time' for time-related functions
from stat import S_ISREG, ST_CTIME, ST_MODE
import os, sys, time
# Determine the directory path based on command-line arguments. If there are two arguments, use the second one as the path; otherwise, use the current directory
dir_path = sys.argv[1] if len(sys.argv) == 2 else r'.'
# Generate a generator expression that yields the full path for each file in the specified directory
data = (os.path.join(dir_path, fn) for fn in os.listdir(dir_path))
# Generate a generator expression that pairs the file's status information and its path
data = ((os.stat(path), path) for path in data)
# Filter the files to keep only regular files (S_ISREG) and extract their creation times (ST_CTIME)
data = ((stat[ST_CTIME], path) for stat, path in data if S_ISREG(stat[ST_MODE]))
# Sort the files based on their creation times and then print the sorted list, including the creation time and the file name
for cdate, path in sorted(data):
  print(time.ctime(cdate), os.path.basename(path))

In [ ]:
# Import the required modules: 'os' for operating system interactions and 'time' for time-related functions
import os
import time

# Create a list 'paths' by iterating through files in the current directory and formatting their creation time and file name
# The list comprehension generates tuples with the creation time and file name for each file
paths = ["%s %s" % (time.ctime(t), f) for t, f in sorted([(os.path.getctime(x), x) for x in os.listdir(".")])]

# Print a header for the directory listing
print("Directory listing, sorted by creation date:")

# Iterate through the list 'paths' and print each entry
for x in range(len(paths)):
  print(paths[x],)

Directory listing, sorted by creation date:
Wed Mar 20 14:52:52 2024 .config
Wed Mar 20 14:52:53 2024 sample_data


## #72
Write a Python program to get the details of the math module

In [ ]:
# Import the math module
import math
# Use the 'dir' function to get a list of names in the 'math' module, including functions and constants
# Store this list in the 'math_ls' variable
math_ls = dir(math)
# Print the list of names in the 'math' module, which includes mathematical functions and constants
print(math_ls)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
# Import the 'math' module to access mathematical functions and constants
import math
# Print a message to provide details about the 'math' module
print("Details of math module:\n")
# Use the 'help' function to display the documentation and details of the 'math' module
# The 'help' function will show information about available functions, constants, and how to use them
help(math)

Details of math module:

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of

## #73
Write a Python program to calculate the midpoints of a line

In [ ]:
# Print a message to inform the user that the program will calculate the midpoint of a line
print('\nCalculate the midpoint of a line: ')

# Prompt the user to enter the x and y coordinates of the first endpoint of the line
x1 = float(input('The value of x (the first endpoint) '))
y1 = float(input('The value of y (the first endpoint) '))

# Prompt the user to enter the x and y coordinates of the second endpoint of the line
x2 = float(input('The value of x (the first endpoint) '))
y2 = float(input('The value of y (the first endpoint) '))

# Calculate the x-coordinate of the midpoint of the line
x_m_point = (x1 + x2)/2

# Calculate the y-coordinate of the midpoint of the line
y_m_point = (y1 + y2)/2
print();

# Print a message to indicate that the program is displaying the midpoint
print("The midpoint of the line is: ")

# Print the x-coordinate of the midpoint
print("The midpoint's x value is: ", x_m_point)

# Print the y-coordinate of the midpoint
print("The midpoint's y value is: ", y_m_point)


Calculate the midpoint of a line: 
The value of x (the first endpoint) 4
The value of y (the first endpoint) 6
The value of x (the first endpoint) 8
The value of y (the first endpoint) 5

The midpoint of the line is: 
The midpoint's x value is:  6.0
The midpoint's y value is:  5.5


## #74
Write a Python program to hash a word

In [ ]:
# Create a list that maps characters to their Soundex codes
soundex = [0, 1, 2, 3, 0, 1, 2, 0, 0, 2, 2, 4, 5, 5, 0, 1, 2, 6, 2, 3, 0, 1, 0, 2, 0, 2]

# Prompt the user to input the word to be hashed
word = input("Input the word to be hashed: ")

# Convert the input word to uppercase
word = word.upper()

# Initialize the coded word with the first character of the input word
coded = word[0]

# Iterate over the remaining characters in the word to calculate the Soundex code
for a in word[1:len(word)]:
  # Calculate the index for Soundex list based on the character's ASCII code
  i = 65 - ord(a)
  coded = coded + str(soundex[i])

# Print a blank line
print()

# Display the coded word
print("The coded word is: " + coded)

# Print a blank line
print()

Input the word to be hashed: watermelon

The coded word is: W000200155



## #75
Write a Python program to get the copyright information and write Copyright information in Python code

In [ ]:
# Import the sys module, which provides access to Python interpreter variables and functions
import sys

# Display a header for Python copyright information
print("\nPython Copyright Information")

# Display the copyright information about Python using sys.copyright
print(sys.copyright)

# Print an empty line for better readability
print()


Python Copyright Information
Copyright (c) 2001-2023 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.



In [ ]:
print("Python copyright information:\n")
print(copyright)

Python copyright information:

Copyright (c) 2001-2023 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.


## #76
Write a Python program to get the command-line arguments (name of the script, the number of arguments, arguments) passed to a script.

In [ ]:
# Import the sys module to access command-line arguments and other system-specific functionality
import sys

# Display the message "This is the name/path of the script:" and print the script's name or path
print("This is the name/path of the script:"), sys.argv[0]

# Display the message "Number of arguments:" and print the total number of command-line arguments
print("Number of arguments:", len(sys.argv))

# Display the message "Argument List:" and print the list of command-line arguments passed to the script
print("Argument List:", str(sys.argv))

This is the name/path of the script:
Number of arguments: 3
Argument List: ['/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-6166181b-793e-4374-aee4-f2caf66df57b.json']


## #77
Write a Python program to test whether the system is a big-endian platform or a little-endian platform

In [ ]:
# Import the sys module to access system-specific information
import sys

# Display a blank line for clarity
print()

# Check if the byte order of the platform is "little" (e.g., Intel, Alpha) and display a corresponding message
if sys.byteorder == "little":
  print("Little-endian platform.")
else:
  # If the byte order is not "little", assume it's "big" (e.g., Motorola, SPARC) and display a corresponding message
  print("Big-endian platform")

# Display another blank line for clarity
print()


Little-endian platform.



## #78
Write a Python program to find the available built-in modules

In [ ]:
# Import the sys module to access system-specific information
import sys

# Import the textwrap module to format the list of module names
import textwrap

# Get a sorted list of built-in module names in the system
module_name = ', '.join(sorted(sys.builtin_module_names))

# Use textwrap to format the list of module names into lines with a maximum width of 70 characters
# Then, print the formatted text
print(textwrap.fill(module_name, width=70))

_abc, _ast, _bisect, _blake2, _codecs, _collections, _csv, _datetime,
_elementtree, _functools, _heapq, _imp, _io, _locale, _md5, _operator,
_pickle, _posixsubprocess, _random, _sha1, _sha256, _sha3, _sha512,
_signal, _socket, _sre, _stat, _statistics, _string, _struct,
_symtable, _thread, _tracemalloc, _warnings, _weakref, array, atexit,
binascii, builtins, cmath, errno, faulthandler, fcntl, gc, grp,
itertools, marshal, math, posix, pwd, pyexpat, select, spwd, sys,
syslog, time, unicodedata, xxsubtype, zlib


## #79
Write a Python program to get the size of an object in bytes

In [ ]:
import sys # Import the sys module to use sys.getsizeof()

# Define three strings and assign values to them
str1 = "one"
str2 = "four"
str3 = "three"
x = 0
y = 112
z = 122.56

# Print the size in bytes of each variable
print("Size of", str1, "=", str(sys.getsizeof(str1)) + " bytes")
print("Size of", str2, "=", str(sys.getsizeof(str2)) + " bytes")
print("Size of", str3, "=", str(sys.getsizeof(str3)) + " bytes")
print("Size of", x, "=", str(sys.getsizeof(x)) + " bytes")
print("Size of", y, "=", str(sys.getsizeof(y)) + " bytes")

# Define a list and assign values to it
L = [1, 2, 3, 'Red', 'Black']

# Print the size in bytes of the list
print("Size of", L, "=", sys.getsizeof(L), "bytes")

# Define a tuple and assign values to it
T = ("Red", [8, 4, 6], (1, 2, 3))

# Print the size in bytes of the tuple
print("Size of", T, "=", sys.getsizeof(T), "bytes")

# Define a set and assign values to it
S = {'apple', 'orange', 'apple', 'pear'}

# Print the size in bytes of the set
print("Size of", S, "=", sys.getsizeof(S), "bytes")

# Define a dictionary and assign values to it
D = {'Name': 'David', 'Age': 6, 'Class': 'First'}

# Print the size in bytes of the dictionary
print("Size of", D, "=", sys.getsizeof(S), "bytes")

Size of one = 52 bytes
Size of four = 53 bytes
Size of three = 54 bytes
Size of 0 = 24 bytes
Size of 112 = 28 bytes
Size of [1, 2, 3, 'Red', 'Black'] = 104 bytes
Size of ('Red', [8, 4, 6], (1, 2, 3)) = 64 bytes
Size of {'orange', 'pear', 'apple'} = 216 bytes
Size of {'Name': 'David', 'Age': 6, 'Class': 'First'} = 216 bytes


## #80
Write a Python program to get the current value of the recursion limit

sys.getrecursionlimit(): Return the current value of the recursion limit, the maximum depth of the Python interpreter stack. This limit prevents infinite recursion from causing an overflow of the C stack and crashing Python. It can be set by setrecursionlimit().

In [ ]:
import sys # Import the sys module to access system-related information

print() # Print a blank line for spacing
print("Current value of the recursion limit:") # Dispaly a message about the recursion limit
print(sys.getrecursionlimit()) # Retrieve and print the current recursion limit
print() # Print a blank line for spacing


Current value of the recursion limit:
1000



## #81
Write a Python program to concatenate N string

In [ ]:
list_of_colors = ['Red', 'White', 'Black'] # Create a list of colors containing three elements
colors = '-'.join(list_of_colors) # Join the list elements with '-' and store the result in the 'colors' variable
print() # Print a blank line for spacing
print("All Colors: " + colors) # Print the concatenated colors with '-' between them
print() # Print another blank line for spacing


All Colors: Red-White-Black



## #82
Write a Python program to calculate the sum of all items of a container (tuple, list, set, dictionary)

Some objects contain references to other objects; these are called containers. Generally, containers provide a way to access the contained objects and to iterate over them. Examples of containers are lists, sets, tuples, and dictionaries.

In [ ]:
# Calculate the sum of the elements in the list [10, 20, 30] using the 'sum' function and store it in the variable 's'
s = sum([10, 20, 30])

# Print a message indicating the sum of the container and display the value of 's'
print("\nSum of the container:", s)

# Print an empty line for better readability
print()


Sum of the container: 60



In [ ]:
# Create a list names 'nums' containing three integer elements: 10, 20, and 30
nums = [10, 20, 30]

# Print a message indicating the original container
print("Original container:")

# Print the 'nums' list, displaying its contents
print(nums)

# Print the data type of the 'nums' list
print(type(nums))

# Print a message indicating the sum of all items in the 'nums' list and compute the sum using the 'sum' function
print("Sum of all items of the said container:", sum(nums))

Original container:
[10, 20, 30]
<class 'list'>
Sum of all items of the said container: 60


In [ ]:
# Define a function 'dict_sum' that takes a dictionary 'nums' as input and calculates the sum of its values
def dict_sum(nums):
  num_sum = 0
  for i in nums:
    num_sum = num_sum + nums[i]
  return num_sum
# Create a dictionary 'nums' with key-value pairs
nums = {'a': 100, 'b': 200, 'c': 300, 'd': 120}
# Print a message indicating the original container and display the dictionary 'nums'
print("Original container:")
print(nums)
# Print the type of the 'nums' container
print(type(nums))
# Calculate the sum of all items in the dictionary 'nums' using the 'dict_sum' function and print the result
print("Sum of all items of the said container:", dict_sum(nums))

Original container:
{'a': 100, 'b': 200, 'c': 300, 'd': 120}
<class 'dict'>
Sum of all items of the said container: 720


In [ ]:
# Create a set 'nums' with a collection of numbers
nums = {7, 4, 9, 1, 3, 2}
# Print a message indicating the original container and display the set 'nums'
print("The original container")
print(nums)
# Print the type of the 'nums' container
print(type(nums))
# Calculate the sum of all items in the set 'nums' using the 'sum' function and store it in the 'sum_tuple' variable
sum_tuple = sum(nums)
# Print the sum of all items in the set
print("Sum of all items of the said container:", str(sum_tuple))

The original container
{1, 2, 3, 4, 7, 9}
<class 'set'>
Sum of all items of the said container: 26


In [ ]:
# Create a tuple 'nums' with a collection of numbers
nums = (7, 4, 9, 1, 3, 2)

# Print a message indicating the original container and display the tuple 'nums'
print("The original container")
print(nums)

# Print the type of the 'nums' container
print(type(nums))

# Calculate the sum of all items in the tuple 'nums' using the 'sum' function and store it in the 'sum_tuple' variable
sum_tuple = sum(nums)

# Print the sum of all items in the tuple
print("SUm of all items of the said container:", str(sum_tuple))

The original container
(7, 4, 9, 1, 3, 2)
<class 'tuple'>
SUm of all items of the said container: 26


## #83
Write a Python program to test whether all numbers in a list are greater than a certain number

In [ ]:
# Create a list 'num' containing integer values
num = [2, 3, 4, 5]

# Print a blank line for better readability
print()

# Check if all elements in the 'num' list are greater than 1 and print the result
print(all(x > 1 for x in num))

# Check if all elements in the 'num' list are greater than 4 and print the result
print(all(x > 4 for x in num))

# Print a blank line for better readability
print()


True
False



In [ ]:
# Define a function 'test' that takes a list 'nums' and an integer 'n' as arguments
# The function checks if all elements in the 'nums' list are greater than 'n' and returns the result
def test(nums, n):
  return(all(x > n for x in nums))

# Create a list 'nums' containing integer values
nums = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# Print the original list of numbers
print("Original list numbers:")
print(nums)

# Set the value fo 'n' to 12
n = 12

# Print a message indicating that we're checking if all numbers in the list are greater than 'n'
print("\nCheck whether all numbers of the said list are greater than", n)

# Call the 'test' function to check if all numbers are greater than 'n' and print the result
print(test(nums, n))

# Set the value of 'n' to 5
n = 5

# Print a message indicating that we're checking if all numbers in the list are greater than 'n'
print("\nCheck whether all numbers of the said list are greater than", n)

# Call the 'test' function again with the updated 'n' value and print the result
print(test(nums, n))

Original list numbers:
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

Check whether all numbers of the said list are greater than 12
False

Check whether all numbers of the said list are greater than 5
True


## #84
Write a Python program to count the number of occurrences of a specific character in a string

In [ ]:
# Create a string 's' containing a sentence
s = "The quick brown fox jumps over the lazy dog"

# Print a message indicating the original string
print("Original string:")

# Print the original string 's'
print(s)

# Print a message indicating the number of occurrences of 'o' in the string
print("Number of occurrences of 'o' in the said string:")

# Print the count of occurrences of the character 'o' in the string 's'.
print(s.count("o"))

Original string:
The quick brown fox jumps over the lazy dog
Number of occurrences of 'o' in the said string:
4


In [ ]:
# Create a string 's' containing a sentence
s = "The quick brown fox jumps over the lazy dog."

# Print a message indicating the original string.
print("Original string:")

# Print the original string 's'
print(s)

# Print a message indicating the number of occurrences of 'o' in the string
print("Number of occurrences of 'o' in the said string:")

# Initialize a counter variable 'ctr' to 0
ctr = 0

# Iterate througheach character 'c' in the string 's'
for c in s:
  # Check if the character 'c' is equal to 'o'
  if c == 'o':
    # If 'c' is 'o', increment the counter 'ctr' by 1
    ctr = ctr + 1

# Print the final count of occurrences of 'o' in the string 's'
print(ctr)

Original string:
The quick brown fox jumps over the lazy dog.
Number of occurrences of 'o' in the said string:
4


## #85
Write a Python program to check whether a file path is a file or a directory

In [ ]:
# Import the 'os' module to access operating system functionalities
import os

# Define the path to a file or directory names 'abc.txt'
path = "abd.txt"

# Check if the path refers to a directory
if os.path.isdir(path):
  # Print a message indicating that it is a directory
  print("\nIt is a directory")

# Check if the path refers to a regular file
elif os.path.isfile(path):
  # Print a message indicating that it is a normal file
  print("\nIt is a normal file")

# If the path doesn't match a directory or a regular file, assume it's a special file (e.g., socket, FIFO, device file).
else:
  # Print a message indicating that it is a special file
  print("It is a special file (socket, FIFO, device file)")

# Print a newline character for spacing
print()

It is a special file (socket, FIFO, device file)



## #86
Write a Python program to get the ASCII value of a character

ASCII (Listeni/ˈæski/ ass-kee), abbreviated from American Standard Code for Information Interchange, is a character encoding standard. ASCII codes represent text in computers, telecommunications equipment, and other devices. Most modern character-encoding schemes are based on ASCII, although they support many additional characters.

In [ ]:
# Print a newline character for spacing
print()

# Print the Unicord code point of the character 'a'
print(ord('a'))

# Print the Unicode code point of the character 'A'
print(ord('A'))

# Print the Unicode code point of the character '1'
print(ord('1'))

# Print the Unicode code point of the character '@'
print(ord('@'))

# Print a newline character for spacing
print()


97
65
49
64



## #87
Write a Python program to get the size of a file

In [ ]:
# Improt the os module for file operations
import os
# Get the size of teh file "abc.txt"
file_size = os.path.getsize("abc.txt")
# Print the size of the file "abc.txt" in bytes
print("\nThe size of abc.txt is:", file_size, "Bytes")
# Print a newline character for spacing
print()

FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'

## #88
Given variables x=30 and y=20, write a Python program to print "30+20=50"

In [ ]:
# Define two variables, x, and y, and assign values 30 and 20, respectively
x = 30
y = 20
# Print the sum of x and y using string formatting
print("\n%d+%d=%d" % (x, y, x+y))


30+20=50


In [ ]:
# Define two variables, x, and y, and assign values 30 and 20, respectively
x = 30
y = 20
# Print the sum of x and y using the format method to insert the variables
print("{0}+{1}={2}".format(x, y, x + y))

30+20=50


In [ ]:
# Define two variables, x, and y, and assign values 30 and 20, respectively
x = 30
y = 20
# Print the sum of x and y using the format method to insert the variables
print("{}+{}={}".format(x, y, x + y))

30+20=50


## #89
Write a Python program to perform an action if a condition is true

Given a variable name, if the value is 1, dispaly the string "First day of a Month!" and do nothing if the value is not equal.

In [ ]:
# Assign the value 1 to the variable n
n = 1
# Check if the value of n is equal to 1
# If the condition is True, print the message indicating the first day of the month
if n == 1:
  print("\nFirst day of a Month!")
# Print an empty line
print()


First day of a Month!



In [ ]:
# Prompt the user to input a number and convert it to a floating-point value
n = float(input("Input a number: "))

# Check if the value of n is equal to 1
# If the condition is True, print the message indicating the first day of the month
if (n == 1):
  print("First day of a Month!")
# If the condition is False, print an empty line
else:
  print()

Input a number: 1
First day of a Month!


In [ ]:
# Define a function named file_copy that takes two arguments: src (source file) and dest (destination file).
def file_copy(src, dest):
    # Use the 'with' statement to open the source file for reading ('r') and the destination file for writing ('w').
    with open(src) as f, open(dest, 'w') as d:
        # Read the content of the source file and write it to the destination file.

# Call the file_copy function with the source file "untitled0.py" and the destination file "z.py".
      file_copy("untitled0.py", "z.py")

# Use the 'with' statement to open the 'z.py' file for reading ('r').
with open('z.py', 'r') as filehandle:
    # Iterate through the lines in the 'z.py' file.
    for line in filehandle:
        # Print each line, and specify 'end' as an empty string to avoid extra line breaks.
        print(line, end = '')

FileNotFoundError: [Errno 2] No such file or directory: 'z.py'

## #91
Write a Python program to swap two variables

In [ ]:
# Initialize two variables 'a' and 'b' with values 30 and 20, respectively
a = 30
b = 20
# Print the values of 'a' and 'b' before swapping, using string formatting
print("\nBefore swap a = %d and b = %d" %(a, b))
# Swap the values of 'a' and 'b' using a tuple assignment. This line effectively swaps the values.
a, b = b, a
# Print the values of 'a' and 'b' after swapping, using string formatting
print("\nAfter swaping a = %d and b = %d" %(a, b))


Before swap a = 30 and b = 20

After swaping a = 20 and b = 30


## #92
Write a Python program to define a string containing special characters in various forms

In [ ]:
# Print a string containing special characters without escaping.
print()
print("\#{'}${\"}@/")

# Print a string containing special characters with escaped single quotes.
print("\#{'}${\"}@/")

# Print a raw string using triple-quotes with special characters.
print(r"""\#{'}${"}@/""")

# Print a string containing special characters without escaping.
print('\#{\'}${"}@/')

# Print a string containing special characters with escaped single quotes.
print('\#{'"'"'}${"}@/')

# Print a raw string using triple-quotes with special characters.
print(r'''\#{'}${"}@/''')
print()


\#{'}${"}@/
\#{'}${"}@/
\#{'}${"}@/
\#{'}${"}@/
\#{'}${"}@/
\#{'}${"}@/



## #93
Write a Python program to get the Identity, Type, and Value of an object

In [ ]:
# Define a variable 'x' and assign the value 34 to it
x = 34

# Print the identity of the variable 'x'
print("\nIdentity: ", x)

# Print the data type of the variable 'x'
print("\nType: ", type(x))

# Print the memeory address (value) of the variable 'x'
print("\nValue: ", id(x))


Identity:  34

Type:  <class 'int'>

Value:  140190283072784


In [ ]:
# Define two variables 'a' and 'b' with some values
a = 34
b = 33
# Print the values of 'a' and 'b'
print('a = ', a)
print('b = ', b)
# Define another variable 'c' and assign the value of 'a' to it
c = a
# Compare the values of 'a' and 'b' for identity
print("compare a and b:")
print(a is b)
# Print the memory address of variable 'a'
print("\nMemeory address of a:")
print(id(a))
# Print the memory address of variable 'b'
print("Memory address of b:")
print(id(b))
# Compare the memory addresses of 'a' and 'b'
print("\nCompare the memory address:")
print(id(a) == id(b))
# Compare the values of 'b' and 'c' for identity
print("\nCompare b and c:")
print(b is c)
# Print the memory address of variable 'c'
print("Memory address of c:")
print(id(c))

a =  34
b =  33
compare a and b:
False

Memeory address of a:
140190283072784
Memory address of b:
140190283072752

Compare the memory address:
False

Compare b and c:
False
Memory address of c:
140190283072784


## #94
Write a Python program to convert the bytes in a given string to a list of integers

In [ ]:
# Create a bytes object containing the bytes 'Abc'
x = b'Abc'

# Print an empty line for clarity
print()

# Convert the bytes of the said string to a list of integers and print the result
print("Convert bytes of the said string to a list of integers:")
print(list(x))

# Print an empty line for clarity
print()


Convert bytes of the said string to a list of integers:
[65, 98, 99]



In [ ]:
# Define a string named S.
S = "The quick brown fox jumps over the lazy dog."

# Print a message indicating the original string
print("Original string:")

# Print the original string
print(S)

# Create an empty list named nums
nums = []

# Print a message to indicate the conversion of bytes to a list of integers
print("\nConvert bytes of the said string to a list of integers:")

# Iterate through each character (byte) in the string S and append its ASCII value to the nums list
for chr in S:
  nums.append(ord(chr))

# Print the list of integers
print(nums)

Original string:
The quick brown fox jumps over the lazy dog.

Convert bytes of the said string to a list of integers:
[84, 104, 101, 32, 113, 117, 105, 99, 107, 32, 98, 114, 111, 119, 110, 32, 102, 111, 120, 32, 106, 117, 109, 112, 115, 32, 111, 118, 101, 114, 32, 116, 104, 101, 32, 108, 97, 122, 121, 32, 100, 111, 103, 46]


## #95
Write a Python program to check whether a string is numeric

In [ ]:
# Define a string named str containing the value 'a123'
str = 'a123'

# Uncomment the line below to test a different string (e.g., '123')
# str = '123'

# Try to convert the string str to a float
try:
  i = float(str)
except (ValueError, TypeError):
  # If a ValueError or TypeError occurs during conversion, print 'Not numeric'
  print('\nNot numeric')

# Print a newline character to format the output
print()

In [ ]:
# Doesn't work for floats
# Prompt the user for input and store it in the 'text' variable
text = input("Input a word or numbers: ")

# Check if the input consists of digits only using the 'isdigit' method
if text.isdigit():
  # If the input contains only digits, print "The input value is numbers."
  print("The input value is numbers.")
else:
  # If the input contains characters other than digits, print "The input value is string"
  print("The input value is string.")

Input a word or numbers: 6513
The input value is numbers.


## #96
Write a Python program to print the current call stack

In [ ]:
# Import the 'trackback' module
import traceback

# Print an empty line for formatting
print()

# Define a function 'f1' that calls the 'abc' function
def f1():
  return abc()

# Define the 'abc' function taht prints the current stack using 'traceback.print_stack()'
def abc():
  traceback.print_stack()

# Call the 'f1' function, which, in turn, calls the 'abc' function
f1()

# Print an empty line for formatting
print()

  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(s

## #97
Write a Python program to list the special variables used in the language

In [ ]:
# Improt the necessary modules

# Create a set 's_var_names' containing unique variable names in the global namespace
s_var_names = sorted((set(globals().keys()) | set(__builtins__.__dict__.keys())) - set('_ names i'.split()))

# Print an empty line for formatting
print()

# Join variable names in groups of 8 and print them for better readability
print('\n'.join(' '.join(s_var_names[i:i+8]) for i in range(0, len(s_var_names), 8)))

# Print an empty line for formatting
print()


ArithmeticError AssertionError AttributeError BaseException BlockingIOError BrokenPipeError BufferError BytesWarning
ChildProcessError ConnectionAbortedError ConnectionError ConnectionRefusedError ConnectionResetError D DeprecationWarning EOFError
Ellipsis EncodingWarning EnvironmentError Exception False FileExistsError FileNotFoundError FloatingPointError
FutureWarning GeneratorExit IOError ImportError ImportWarning In IndentationError IndexError
InterruptedError IsADirectoryError KeyError KeyboardInterrupt L LookupError MemoryError ModuleNotFoundError
NameError None NotADirectoryError NotImplemented NotImplementedError OSError Out OverflowError
PendingDeprecationWarning PermissionError ProcessLookupError RecursionError ReferenceError ResourceWarning RuntimeError RuntimeWarning
S StopAsyncIteration StopIteration SyntaxError SyntaxWarning SystemError SystemExit T
TabError TimeoutError True TypeError UnboundLocalError UnicodeDecodeError UnicodeEncodeError UnicodeError
UnicodeTranslateE

## #98
Write a Python program to get system time

Note: The system time is important for debugging, network information, random number seeds, or something as simple as program performance

In [ ]:
# Import the 'time' module to work with time-related functions
import time

# Print an empty line for formatting
print()

# Get and print the current time using 'time.ctime()'
print(time.ctime())

# Print an empty line for formatting
print()


Fri Mar 22 19:50:21 2024



In [ ]:
import datetime
print(datetime.datetime.now())

2024-03-22 19:50:39.913779


## #99
Write a Python program to clear the screen or terminal

In [ ]:
# Import the 'os' and 'time' modules to work with system commands and time-related functions, respectively
import os
import time

# Execute the 'ls' command to list the contents of the current directory
os.system("ls")

# Paus the program's execution for 2 seconds
time.sleep(2)

# Clear the terminal screen. (This comment is not entirely accurate; 'os.system('clear')' is used to clear the terminal screen.)
os.system('clear')

0

## #100
Write a Python program to get the name of the host on which the routine is running

In [ ]:
# Import the 'socket' module to work with networking functionalities

import socket
# Use 'socket.gethostname()' to retrieve the name of the current host or machine
host_name = socket.gethostname()

# Print the host name to the console
print("Host name:", host_name)

Host name: 11fb4831fb7b


In [ ]:
# Import the 'platform' module to retrieve system-related information
import platform
# Use 'platform.uname()' to obtain a tuple of information about the system, including the host name
host_name = platform.uname()[1]

# Print the host name to the console
print("Host name:", host_name)

Host name: 11fb4831fb7b


In [ ]:
# Import the 'os' module to access operating system-related functionality
import os
# Use 'os.uname().nodename' to retrienve the host name of the current system
host_name = os.uname().nodename
# Print the host name to the console
print("Host name:", host_name)

Host name: 11fb4831fb7b


## #101
Write a Python program to access and print a URL's content to the console.

In [43]:
# Import the HTTPConnection class from the http.client module.
from http.client import HTTPConnection

# Create an HTTPConnection object for the "example.com" host.
conn = HTTPConnection("example.com")

# Send a GET request to the root path ("/") of the host.
conn.request("GET", "/")

# Get the response from the server.
result = conn.getresponse()

# Retrieve the entire contents of the response.
contents = result.read()

# Print the contents of the response.
print(contents)


b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    

In [44]:
# Import the requests library to make HTTP requests.
import requests

# Send an HTTP GET request to the 'https://google.com/' URL and store the response.
data = requests.get('https://google.com/')

# Access the text content of the response, which contains the webpage's HTML.
webpage_text = data.text

# Print the HTML content of the webpage.
print(webpage_text)


<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp, " name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="c6ba7Uq0tHU-8B221YzqUg">(function(){var _g={kEI:'InEEZryvFuuhur8Pjsa38Ao',kEXPI:'0,1365467,207,4804,2329829,642,361,379729,35511,9287,36110,17581,4998,55519,2872,2891,3926,4423,3405,30448,30848,6398,8926,2025,1,16916,2652,4,62597,24013,6681,7596,1,11942,30212,2,16395,342,23024,6699,31123,4567,6259,24670,33064,2,2,1,24626,2006,8155,8860,14490,22436,9779,12415,30044,20199,36746,3801,2412,6264,23955,3030,15816,1804,7734,25,18073,21250,1634,8840,33427,14093,5203197,13,6929,2,297,109

## #102
Write a Python program to get system command output.

In [45]:
# Import the subprocess module to run shell commands.
import subprocess
# Use the 'subprocess.check_output' function to execute the 'dir' command in the shell.
# 'universal_newlines=True' ensures text mode for cross-platform compatibility.
returned_text = subprocess.check_output("dir", shell=True, universal_newlines=True)
# Print a message indicating the purpose of running the 'dir' command.
print("dir command to list files and directories")
# Print the output (list of files and directories) returned by the 'dir' command.
print(returned_text)


dir command to list files and directories
sample_data



## #103
Write a Python program to extract the filename from a given path.

In [46]:
# Import the 'os' module for operating system-related functions.
import os

# Print a newline for clarity.
print()

# Use 'os.path.basename' to extract the filename component from the given path.
# In this case, it extracts the filename 'homework-1.py' from the provided path.
print(os.path.basename('/users/system1/student1/homework-1.py'))

# Print another newline for clarity.
print()



homework-1.py



## #104
Write a Python program to get the effective group id, effective user id, real group id, and a list of supplemental group ids associated with the current process.

In [47]:
# Import the 'os' module for operating system-related functions.
import os

# Print a newline for clarity.
print()

# Get the effective group ID and print it.
print("Effective group id: ", os.getegid())

# Get the effective user ID and print it.
print("Effective user id: ", os.geteuid())

# Get the real group ID and print it.
print("Real group id: ", os.getgid())

# Get the list of supplemental group IDs and print them.
print("List of supplemental group ids: ", os.getgroups())

# Print another newline for clarity.
print()



Effective group id:  0
Effective user id:  0
Real group id:  0
List of supplemental group ids:  [0]



## #105
Write a Python program to get the users environment.

In [48]:
# Import the 'os' module for operating system-related functions.
import os

# Print a newline for clarity.
print()

# Access and print the environment variables as a dictionary.
print(os.environ)

# Print another newline for clarity.
print()



environ({'SHELL': '/bin/bash', 'NV_LIBCUBLAS_VERSION': '12.2.5.6-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'COLAB_JUPYTER_TRANSPORT': 'ipc', 'NV_NVML_DEV_VERSION': '12.2.140-1', 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8', 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events', 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.19.3-1+cuda12.2', 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.19.3-1', 'VM_GCE_METADATA_HOST': '169.254.169.253', 'HOSTNAME': '4277a4261f3c', 'LANGUAGE': 'en_US', 'TBE_RUNTIME_ADDR': '172.28.0.1:8011', 'COLAB_TPU_1VM': '', 'GCE_METADATA_TIMEOUT': '3', 'NVIDIA_REQUIRE_CUDA': 'cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,d

In [49]:
# Import the 'os' module for operating system-related functions.
import os

# Import the 'pprint' module for pretty-printing data structures.
import pprint

# Access and store the user's environment variables.
u_env_var = os.environ

# Print a message indicating the user's environment variables.
print("User's Environment variable:")

# Pretty-print the environment variables in a more readable format.
pprint.pprint(dict(u_env_var), width=1)


User's Environment variable:
{'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events '
                         '/var/colab/cgroup/jupyter-children/memory.events',
 'CLICOLOR': '1',
 'CLOUDSDK_CONFIG': '/content/.config',
 'CLOUDSDK_PYTHON': 'python3',
 'COLAB_BACKEND_VERSION': 'next',
 'COLAB_DEBUG_ADAPTER_MUX_PATH': '/usr/local/bin/dap_multiplexer',
 'COLAB_FILE_HANDLER_ADDR': 'localhost:3453',
 'COLAB_GPU': '',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_JUPYTER_TOKEN': '',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'COLAB_KERNEL_MANAGER_PROXY_PORT': '6000',
 'COLAB_LANGUAGE_SERVER_PROXY': '/usr/colab/bin/language_service',
 'COLAB_LANGUAGE_SERVER_PROXY_LSP_DIRS': '/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'COLAB_RELEASE_TAG': 'release-colab_20240326-060120_RC00',
 'COLAB_T

In [50]:
# Import the 'os' module for accessing environment variables.
import os

# Retrieve the 'HOSTNAME' environment variable.
host_name = os.environ['HOSTNAME']

# Print the value of the 'HOSTNAME' environment variable.
print("HOSTNAME:", host_name)

# Retrieve the 'PYTHONPATH' environment variable.
python_path = os.environ.get('PYTHONPATH')

# Print the value of the 'PYTHONPATH' environment variable.
print("Python Path:", python_path)


HOSTNAME: 4277a4261f3c
Python Path: /env/python


## #106
Write a Python program to divide a path by the extension separator.

In [51]:
# Import the 'os.path' module for working with file paths.
import os.path
# Iterate through a list of example file paths.
for path in ['test.txt', 'filename', '/user/system/test.txt', '/', '']:
    # Print the file path and its corresponding file extension using 'os.path.splitext()'.
    print('"%s" :' % path, os.path.splitext(path))


"test.txt" : ('test', '.txt')
"filename" : ('filename', '')
"/user/system/test.txt" : ('/user/system/test', '.txt')
"/" : ('/', '')
"" : ('', '')


## #107
Write a Python program to retrieve file properties.

In [52]:
# Import the 'os.path' and 'time' modules for working with file paths and time-related functions.
import os.path
import time
# Print the name of the current file using '__file__' attribute.
print('File         :', __file__)

# Print the access time of the current file using 'os.path.getatime()' and 'time.ctime()'.
print('Access time  :', time.ctime(os.path.getatime(__file__)))

# Print the modified time of the current file using 'os.path.getmtime()' and 'time.ctime()'.
print('Modified time:', time.ctime(os.path.getmtime(__file__)))

# Print the change time of the current file using 'os.path.getctime()' and 'time.ctime()'.
print('Change time  :', time.ctime(os.path.getctime(__file__)))

# Print the size of the current file using 'os.path.getsize()'.
print('Size         :', os.path.getsize(__file__))


NameError: name '__file__' is not defined

## #108
Write a Python program to find the path to a file or directory when you encounter a path name.

In [53]:
# Import the 'os.path' module for working with file paths.
import os.path
# Iterate through a list of file paths, including '__file__', the directory of '__file__', '/', and a broken link.
for file in [__file__, os.path.dirname(__file__), '/', './broken_link']:
    # Print the name of the current file.
    print('File        :', file)

    # Check if the file path is an absolute path using 'os.path.isabs()'.
    print('Absolute    :', os.path.isabs(file))

    # Check if the file path points to an existing file using 'os.path.isfile()'.
    print('Is File?    :', os.path.isfile(file))

    # Check if the file path points to an existing directory using 'os.path.isdir()'.
    print('Is Dir?     :', os.path.isdir(file))

    # Check if the file path is a symbolic link using 'os.path.islink()'.
    print('Is Link?    :', os.path.islink(file))

    # Check if the file path exists (regardless of its type) using 'os.path.exists()'.
    print('Exists?     :', os.path.exists(file))

    # Check if the symbolic link exists using 'os.path.lexists()'.
    print('Link Exists?:', os.path.lexists(file))


NameError: name '__file__' is not defined

## #109
Write a Python program to check if a number is positive, negative or zero.

Positive Numbers: Any number above zero is known as a positive number. Positive numbers are written without any sign or a '+' sign in front of them and they are counted up from zero, i.e. 1, + 2, 3, +4 etc.
Negative Numbers: Any number below zero is known as a negative number. Negative numbers are always written with a '−' sign in front of them and they are counted down from zero, i.e. -1, -2, -3, -4 etc.
Always look at the sign in front of a number to check if it is positive or negative. Zero, 0, is neither positive nor negative.

In [54]:
# Prompt the user to input a number, and convert the input to a floating-point number.
num = float(input("Input a number: "))

# Check if the number is greater than zero.
if num > 0:
   # If true, print that it is a positive number.
   print("It is a positive number")
# Check if the number is equal to zero.
elif num == 0:
   # If true, print that it is zero.
   print("It is zero")
else:
   # If the above conditions are not met, print that it is a negative number.
   print("It is a negative number")


Input a number: 15
It is a positive number


In [55]:
# Prompt the user to input a number and convert the input to a floating-point number.
n = float(input('Input a number: '))

# Use a conditional expression (ternary operator) to determine if the number is positive, zero, or negative.
# The conditional expression checks if the number is greater than 0, equal to 0, or less than 0.
# Depending on the condition met, it prints a corresponding message.
print('Number is Positive.' if n > 0 else 'It is Zero!' if n == 0 else 'Number is Negative.')


Input a number: 0
It is Zero!


In [56]:
# Prompt the user to input a number and convert the input to a floating-point number.
n = float(input("Input a number: "))

# Check if the input number is greater than or equal to 0.
if n >= 0:
    # If the number is zero, print that it is zero.
    if n == 0:
        print("It is Zero!")
    # If the number is greater than zero, print that it is a positive number.
    else:
        print("Number is Positive number.")
# If the number is less than zero, print that it is a negative number.
else:
    print("Number is Negative number.")


Input a number: -8
Number is Negative number.


## #110
Write a Python program to get numbers divisible by fifteen from a list using an anonymous function.

In [57]:
# Create a list of numbers.
num_list = [45, 55, 60, 37, 100, 105, 220]

# Use an anonymous lambda function with the filter function to filter numbers in the list that are divisible by 15.
result = list(filter(lambda x: (x % 15 == 0), num_list))

# Print the numbers that are divisible by 15.
print("Numbers divisible by 15 are", result)


Numbers divisible by 15 are [45, 60, 105]


In [58]:
# Create a list of numbers.
num_list = [45, 55, 60, 37, 100, 105, 220]

# Print the original list of numbers.
print("Original list:", num_list)

# Use an anonymous lambda function with the filter function to filter numbers in the list that are divisible by 15.
result = list(filter(lambda x: (x % 15 == 0), num_list))

# Print the numbers from the original list that are divisible by 15.
print("Numbers of the said list divisible by 15 are:", result)


Original list: [45, 55, 60, 37, 100, 105, 220]
Numbers of the said list divisible by 15 are: [45, 60, 105]


In [2]:
# Create a list of numbers.
num_list = [45, 55, 60, 37, 100, 105, 220]

# Print the original list of numbers.
print("Original list:", num_list)

# Print a message indicating the list of numbers divisible by 15 will be displayed.
print("\nNumbers of the said list divisible by 15 are:")

# Filter the numbers in the list that are divisible by 15 using a list comprehension and a lambda function.
# Convert the resulting list to a string and join it to a single string without spaces.
result = str(''.join(filter(lambda x: x, str(list([i for i in num_list if i % 15 == 0])))))

# Print the concatenated result.
print(result)


Original list: [45, 55, 60, 37, 100, 105, 220]

Numbers of the said list divisible by 15 are:
[45, 60, 105]


## #111
Write a Python program to make file lists from the current directory using a wildcard.

In [3]:
# Import the glob module, which allows you to search for files using wildcard patterns
import glob

# Use the glob module to get a list of all files in the current directory
file_list = glob.glob('*.*')

# Print the list of all files in the current directory
print(file_list)

# Specific files
# Use a wildcard pattern to search for Python (.py) files in the current directory
print(glob.glob('*.py'))

# Use a more specific pattern to search for files with names starting with a digit and any extension
print(glob.glob('./[0-9].*'))


[]
[]
[]


In [4]:
# Import the Path class from the pathlib module to work with file paths
from pathlib import Path
# Iterate over all files and directories in the root directory ("/")
for path in Path("/").glob("*.*"):
    # Print the path (file or directory) to the console
    print(path)


/.dockerenv
/cuda-keyring_1.0-1_all.deb


## #112
Write a Python program to remove the first item from a specified list.

In [5]:
# Create a list of color names
color = ["Red", "Black", "Green", "White", "Orange"]

# Print the original list elements
print("Original list elements:")
print(color)

# Remove the first element (element at index 0) from the list
del color[0]
# Print the list after removing the first color
print("After removing the first color: ")
print(color)
print()


Original list elements:
['Red', 'Black', 'Green', 'White', 'Orange']
After removing the first color: 
['Black', 'Green', 'White', 'Orange']



In [6]:
# Create a list of color names
color = ["Red", "Black", "Green", "White", "Orange"]

# Print the original list elements
print("Original list elements:")
print(color)

# Print a message indicating the operation that will be performed
print("\nAfter removing the first element from the said list:")

# Create a new list 'new_color' by slicing the original list from the second element (index 1) to the end
new_color = color[1:]

# Print the modified list after removing the first element
print(new_color)


Original list elements:
['Red', 'Black', 'Green', 'White', 'Orange']

After removing the first element from the said list:
['Black', 'Green', 'White', 'Orange']


In [7]:
# Create a list of color names
color = ["Red", "Black", "Green", "White", "Orange"]

# Print a message indicating the original list elements
print("Original list elements:")

# Print the original list elements
print(color)

# Print a message indicating the operation that will be performed
print("\nAfter removing the first element from the said list:")

# Remove the element "Red" from the list
color.remove("Red")

# Print the modified list after removing the element
print(color)


Original list elements:
['Red', 'Black', 'Green', 'White', 'Orange']

After removing the first element from the said list:
['Black', 'Green', 'White', 'Orange']


In [8]:
# Define a function named "tail" that takes a list "lst" as input.
def tail(lst):
  # Check if the length of the list is greater than 1.
  if len(lst) > 1:
    # If the list has more than one element, return a new list containing all elements except the first one.
    return lst[1:]
  else:
    # If the list has only one element or is empty, return the original list.
    return lst

# Call the "tail" function with different lists and print the results.
print(tail([1, 2, 3, 4]))  # Should print [2, 3, 4]
print(tail([1]))          # Should print [1] (no change)
print(tail(["Red", "Black", "Green", "White", "Orange"]))  # Should print ["Black", "Green", "White", "Orange"]


[2, 3, 4]
[1]
['Black', 'Green', 'White', 'Orange']


## #113
Write a Python program that inputs a number and generates an error message if it is not a number.

In [9]:
# Create an infinite loop using "while True."
while True:
    try:
        # Try to read an integer input from the user and store it in variable "a."
        a = int(input("Input a number: "))
        # If successful, break out of the loop and continue with the next code.
        break
    except ValueError:
        # If the input is not a valid integer, an exception (ValueError) is raised.
        # In that case, print an error message and prompt the user to try again.
        print("\nThis is not a number. Try again...")
        print()


Input a number: dbs

This is not a number. Try again...

Input a number: afe

This is not a number. Try again...

Input a number: 185


In [10]:
# Define a variable "x" and initialize it with the float value 1.23.
x = 1.23

# Check if "x" is an integer by using the "is_integer()" method, which returns a boolean value.
x_int = x.is_integer()

# Print a message to indicate that we are checking if "x" is an integer.
print("Check if x is an integer!")

# Print the result of the check for "x" being an integer.
print(x_int)

# Define a variable "y" and initialize it with the float value 1.0.
y = 1.0

# Check if "y" is an integer by using the "is_integer()" method, which returns a boolean value.
y_int = y.is_integer()

# Print a message to indicate that we are checking if "y" is an integer.
print("Check if y is an integer!")

# Print the result of the check for "y" being an integer.
print(y_int)


Check if x is an integer!
False
Check if y is an integer!
True


In [11]:
# Define a variable "x" and initialize it with the float value 1.0.
x = 1.0

# Check if "x" is an integer by using the "isinstance()" function, which returns a boolean value.
x_int = isinstance(x, int)

# Print a message to indicate that we are checking if "x" is an integer.
print("Check if x is an integer!")

# Print the result of the check for "x" being an integer.
print(x_int)

# Define a variable "y" and initialize it with the integer value 1.
y = 1

# Check if "y" is an integer by using the "isinstance()" function, which returns a boolean value.
y_int = isinstance(y, int)

# Print a message to indicate that we are checking if "y" is an integer.
print("Check if y is an integer!")

# Print the result of the check for "y" being an integer.
print(y_int)


Check if x is an integer!
False
Check if y is an integer!
True


## #114
Write a Python program to filter positive numbers from a list.

Positive Numbers: Any number above zero is known as a positive number. Positive numbers are written without any sign or a '+' sign in front of them and they are counted up from zero, i.e. 1, + 2, 3, +4 etc.

In [12]:
# Define a list named "nums" containing a series of integers.
nums = [34, 1, 0, -23, 12, -88]

# Print a message along with the original list of numbers.
print("Original numbers in the list: ", nums)

# Create a new list "new_nums" by using the "filter" function with a lambda function
# that filters out positive numbers from the "nums" list.
new_nums = list(filter(lambda x: x > 0, nums))

# Print a message along with the list of positive numbers from the "nums" list.
print("Positive numbers in the said list: ", new_nums)


Original numbers in the list:  [34, 1, 0, -23, 12, -88]
Positive numbers in the said list:  [34, 1, 12]


In [13]:
# Define a list named "nums" containing a series of integers.
nums = [34, 1, 0, -23, 12, -88]

# Print a message along with the original list of numbers.
print("Original numbers in the list: ", nums)

# Print a message indicating that positive numbers in the list will be listed.
print("Positive numbers in the said list: ")

# Iterate through each number in the "nums" list.
for pos_nums in nums:
    # Check if the number is greater than 0 (positive).
    if pos_nums > 0:
        # Print positive numbers on the same line with a space separator.
        print(pos_nums, end=" ")


Original numbers in the list:  [34, 1, 0, -23, 12, -88]
Positive numbers in the said list: 
34 1 12 

In [14]:
# Define a list named "nums" containing a series of integers.
nums = [34, 1, 0, -23, 12, -88]

# Print a message along with the original list of numbers.
print("Original numbers in the list: ", nums)

# Create a new list "pos_nums" using a list comprehension to filter positive numbers from "nums."
# Positive numbers are those greater than 0.
pos_nums = [n for n in nums if n > 0]

# Print a message indicating that positive numbers in the list will be listed,
# followed by the positive numbers separated by a space.
print("Positive numbers in the said list: ", *pos_nums)


Original numbers in the list:  [34, 1, 0, -23, 12, -88]
Positive numbers in the said list:  34 1 12


## #115
Write a Python program to compute the product of a list of integers (without using a for loop).

In [15]:
# Import the 'reduce' function from the 'functools' module.
from functools import reduce

# Define a list named 'nums' containing a series of integers.
nums = [10, 20, 30]

# Print a message along with the original list of numbers.
print("Original list numbers:")
print(nums)

# Calculate the product of the numbers in the list 'nums' using the 'reduce' function
# and a lambda function that multiplies two numbers.
nums_product = reduce((lambda x, y: x * y), nums)

# Print the product of the numbers, obtained without using a for loop.
print("\nProduct of the said numbers (without using a for loop):", nums_product)


Original list numbers:
[10, 20, 30]

Product of the said numbers (without using a for loop): 6000


In [16]:
# Import the 'math' module to access the 'prod' function.
import math

# Define a list named 'nums' containing a series of integers.
nums = [10, 20, 30]

# Print a message indicating the original list of numbers.
print("Original list numbers:")
print(nums)

# Calculate the product of the numbers in the list 'nums' using the 'prod' function
# from the 'math' module.
nums_product = math.prod(nums)

# Print the product of the numbers, obtained without using a for loop.
print("\nProduct of the said numbers (without using a for loop):", nums_product)


Original list numbers:
[10, 20, 30]

Product of the said numbers (without using a for loop): 6000


## #116
Write a Python program to print Unicode characters.

In [17]:
# Create a Unicode string by specifying each character's Unicode escape sequence.
str = u'\u0050\u0079\u0074\u0068\u006f\u006e \u0045\u0078\u0065\u0072\u0063\u0069\u0073\u0065\u0073 \u002d \u0077\u0033\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065'

# Print a blank line for separation.
print()

# Print the Unicode string, which will be displayed as "Python Exercises - w3resource".
print(str)

# Print another blank line for separation.
print()



Python Exercises - w3resource



## #117
Write a Python program to prove that two string variables of the same value point to the same memory location.

In [18]:
# Define two string variables, str1 and str2, both containing the string "Python".
str1 = "Python"
str2 = "Python"

# Print the memory location (in hexadecimal) of str1 and str2 using the id() function.
print("\nMemory location of str1 =", hex(id(str1)))
print("Memory location of str2 =", hex(id(str2)))

# Print a blank line for separation.
print()



Memory location of str1 = 0x7de1d8ac75b0
Memory location of str2 = 0x7de1d8ac75b0



## #118
Write a Python program to create a bytearray from a list.

In [19]:
# Print a blank line for separation.
print()

# Create a list of integers called nums.
nums = [10, 20, 56, 35, 17, 99]

# Create a bytearray from the list of integers.
values = bytearray(nums)

# Iterate through the elements of the bytearray and print each element.
for x in values:
    print(x)

# Print a blank line for separation.
print()



10
20
56
35
17
99



## #119
Write a Python program to round a floating-point number to a specified number of decimal places.

In [20]:
# Define the order amount as a floating-point number.
order_amt = 212.374

# Print the total order amount with 6 decimal places.
print('\nThe total order amount comes to %f' % order_amt)

# Print the total order amount with 2 decimal places using string formatting.
print('The total order amount comes to %.2f' % order_amt)

# Print a blank line for formatting.
print()



The total order amount comes to 212.374000
The total order amount comes to 212.37



In [21]:
# Define the order amount as a floating-point number.
order_amt = 212.374

# Print the total order amount with 6 decimal places using format.
print("\nThe total order amount comes to {:0.6f}".format(order_amt))

# Print the total order amount with 2 decimal places using format.
print("\nThe total order amount comes to {:0.2f}".format(order_amt))



The total order amount comes to 212.374000

The total order amount comes to 212.37


## #120
Write a Python program to format a specified string and limit the length of a string.

In [22]:
# Define a string containing a numeric value.
str_num = "1234567890"

# Print the original string.
print("Original string:", str_num)

# Print the first 6 characters of the string.
print('%.6s' % str_num)

# Print the first 9 characters of the string.
print('%.9s' % str_num)

# Print the entire string (first 10 characters) as it is.
print('%.10s' % str_num)


Original string: 1234567890
123456
123456789
1234567890


## #121
Write a Python program to determine if a variable is defined or not

In [25]:
# Try to execute a block of code
try:
  x = 1
except NameError:
  print("Variable is not defined....!")
else:
  print("Variable is defined.")

# Try to execute another block of code that references an undefined variable
try:
  fry
except NameError:
  print("Variable is not defined....!")
else:
  print("Variable is defined.")

Variable is defined.
Variable is not defined....!


## #122
Write a Python program to empty a variable without destroying it

type() returns the type of an object, which when called produces an 'empty' new value

Sample data: n=20
d = {"x":200}
Expected Output: 0
{}

In [26]:
# Define a variable n with a value of 20.
n = 20

# Define a dictionary d with a key "x" and a value of 200
d = {"x": 200}

# Define a list 1 with elements 1, 3, and 5
l = [1, 3, 5]

# Define a tuple t with elements 5, 7, and 8
t = (5, 7, 8)

# Print the type of n and create an instance of that type with no arguments
print(type(n)())

# Print the type of d and create an instance of that type with no arguments
print(type(d)())

# Print the type of l and create an instance of that type with no arguments
print(type(l)())

# Print the type of t and create an instance of that type with no arguments
print(type(t)())

0
{}
[]
()


In [29]:
# Define a function called Empty_Var that takes a list lst as input
def Empty_Var(lst):
  # Create a new list by initializing elements of the same type as those in the input list
  return [type(i)() for i in lst]

# Create a list called lst containing various types of objects
lst = ["python", {"x": 12}, [10, 12, "sfsd"], (4, 5), 200]

# Print the original objects contained in the list
print("Original objects:")
print(lst)

# Print a message and result of emptying the variables without destroying them
print("\nEmpty the said variables without destroying them:")
print(Empty_Var(lst))

Original objects:
['python', {'x': 12}, [10, 12, 'sfsd'], (4, 5), 200]

Empty the said variables without destroying them:
['', {}, [], (), 0]


## #123
Write a Python program to determine the largest and smallest integers, longs, and floats

In [30]:
# Import the sys module to access system-related information
import sys

# Print information about the float data type
print("Float value information: ", sys.float_info)

# Print information about the data type (Note: there is no sys.int_info, this is incorrect)
print("\nInteger value information: ", sys.int_info)

# Print the maximum size of an integer that can be represented on the current system
print("\nMaximum size of an integer: ", sys.maxsize)

Float value information:  sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

Integer value information:  sys.int_info(bits_per_digit=30, sizeof_digit=4, default_max_str_digits=4300, str_digits_check_threshold=640)

Maximum size of an integer:  9223372036854775807


## #124
Write a Python program to check whether multiple variables have the same value

In [31]:
# Assign the value 20 to the variable x
x = 20

# Assign the value 20 to the variable y
y = 20

# Assign the value 20 to the variable z
z = 20

# Check if all variables have the value 20 using the equality (==) operator
if x == y == z == 20:
  print("All variables have the same value!")

All variables have the same value!


In [32]:
# Define a function that checks if all variables passed as arguments have the same value
def multiple_variables_equality(*vars):
  # Iterate through the variables in the argument list
  for x in vars:
    # Check if the current variable is not equal to the first variable
    if x != vars[0]:
      return "All variables do not have the same value."
  return "All variables have the same value."

# Call the function with different sets of variables and print the result
print(multiple_variables_equality(2, 3, 2, 2, 2, 2))
print(multiple_variables_equality(10, 10, 10, 10))
print(multiple_variables_equality(-3, -3, -3, -3))

All variables do not have the same value.
All variables have the same value.
All variables have the same value.


## #125
Write a Python program to sum all counts in a collection

In [33]:
# Import the 'collections' module, which provides the 'Counter' class
import collections

# Define a list of numbers
num = [2, 2, 4, 6, 6, 8, 6, 10, 4]

# Use 'collections.Counter' to count the occurrences of each number and sum the values
# 'sum(collections.Counter(num).values())' calculates the sum of these counts
result = sum(collections.Counter(num).values())

# Print the result, which is the sum of the counts
print(result)

9


In [34]:
# Create a list 'nums' containing various integer values
nums = [2, 2, 4, 6, 6, 8, 6, 10, 4]

# Calculate and print the length (number of elements) of the 'nums' list
print(len(nums))

9


## #126
Write a Python program to get the actual module object for a given object

In [35]:
# Import the 'getmodule' function from the 'inspect' module
from inspect import getmodule

# Import the 'sqrt' function from the 'math' module
from math import sqrt

# Use the 'getmodule' function to get the module where the 'sqrt' function is defined
# Then, print the module information for the 'sqrt' function
print(getmodule(sqrt))

<module 'math' (built-in)>


In [36]:
# Import the 'inspect' module
import inspect

# Define a function named 'add' that takes two arguments, 'x' and 'y'
def add(x, y):
  return x + y

# Use the 'inspect.getmodule' function to get the module where the 'add' function is defined
# Then, print the module information for the 'add' function
print(inspect.getmodule(add))

<module '__main__'>


## #127
Write a Python program to check whether an integer fits in 64 bits

In [38]:
# Assign the integer value 30 to the variable 'int_val'.
int_val = 30

# Check if the bit length of 'int_val' is less than or equal to 63.
if int_val.bit_length() <= 63:
    # Print the bit length of the minimum 64-bit signed integer (-2^63).
    print((-2 ** 63).bit_length())

    # Print the bit length of the maximum 64-bit signed integer (2^63 - 1).
    print((2 ** 63).bit_length())

64
64


## #128
Write a Python program to check whether lowercase letters exist in a string

In [39]:
# ASsign the string 'A8238i823acdeOUEI' to the variable 'str1'
str1 = 'A8238i823acdeOUEI'

# Check if there is any lowercase character in the string 'str1'
# The 'any' function returns True if at least one character is lowercase
print(any(c.islower() for c in str1))

True


In [40]:
# Define a function 'lower_case_str' that takes a text as input
def lower_case_str(text):
  # Initalize a counter variable 'ctr' to keep track of lowercase characters
  ctr = 0

  # Iterate through each character in the 'text'
  for char in text:
    # Check if the character's Unicode value falls within the lowercase letters range
    if (ord(char) >= 97 and ord(char) <= 122):
      ctr = ctr + 1

  # If 'ctr' is greater than 0, it means at least one lowercase character was found
  if (ctr > 0):
    return True

# Define a string 'str1' with mixed characters
str1 = 'A8238i823acdeOUEI'
print("Original string:", str1)

# Call the 'lower_case_str' function to check if lowercase letters exist in 'str1'
print("Lowercase letters exist in the said string: ", lower_case_str(str1))

# Repeat the above steps for different strings
str1 = 'PYTHON'
print("\nOriginal string:", str1)
print("Lowercase letters exist in the said string: ", lower_case_str(str1))

str1 = 'javascript'
print("\nOriginal string:", str1)
print("Lowercase letters exist in the said string: ", lower_case_str(str1))

Original string: A8238i823acdeOUEI
Lowercase letters exist in the said string:  True

Original string: PYTHON
Lowercase letters exist in the said string:  None

Original string: javascript
Lowercase letters exist in the said string:  True


In [42]:
# Define a function 'lower_case_str' that takes a text as input
def lower_case_str(text):
  # Check if the entire text is in lowercase using 'islower()' method
  if text.islower():
    return True
  return False

# Print a message to indicate the purpose of the code
print("Check if all input alphabets are small!")

# Define a string 'str1' with mixed characters
str1 = 'A8238i823acdeOUEI'
print("\nOriginal string:", str1)

# Call the 'lower_case_str' function to check if all characters in 'str1' are lowercase
print("Lowercase letters in the said string: ", lower_case_str(str1))

# Repeat the above steps for different strings
str1 = 'PYTHON'
print("\nOriginal string:", str1)
print("Lowercase letters exist in the said string: ", lower_case_str(str1))

str1 = 'javascript'
print("\nOriginal string:", str1)
print("Lowercase letters exist in the said string: ", lower_case_str(str1))

Check if all input alphabets are small!

Original string: A8238i823acdeOUEI
Lowercase letters in the said string:  False

Original string: PYTHON
Lowercase letters exist in the said string:  False

Original string: javascript
Lowercase letters exist in the said string:  True


## #129
Write a Python program to add leading zeroes to a string

In [43]:
# Define the original string 'str1'
str1 = '122.22'
print("Original String: ", str1)

# Print a message to indicate the prupose of the code
print("\nAdded trailling zeros:")

# Use the 'ljust' method to add trailling zeros to 'str1' to make its total width 8
str1 = str1.ljust(8, '0')
print(str1)

# Repeat the process to make the total width 10
str1 = str1.ljust(10, '0')
print(str1)

# Print a message to indicate the addition of leading zeros
print("\nAdded leading zeros:")

# Reset 'str1' to the original value
str1 = '122.22'

# Use the 'rjust' method to add leading zeros to 'str1' to make its total width 8
str1 = str1.rjust(8, '0')
print(str1)

# Repeat the process to make the total width 10
str1 = str1.rjust(10, '0')
print(str1)

Original String:  122.22

Added trailling zeros:
122.2200
122.220000

Added leading zeros:
00122.22
0000122.22


In [47]:
# Define the original string 'str1'
str1 = '122.22'
print("Original String: ", str1)

# Print a message to indicate the purpose of the code
print("\nAdded trailling zeros:")

# Define a format text with left alignment and total width of 8
f_text = '{:<08}'

# Use the 'format' method to add trailing zeros to 'str1' according to the format text
str1 = f_text.format(str1)
print(str1)

# Define a format text with left alignment and total width of 10
f_text = '{:<010}'

# Repeat the process to make the total width 10
str1 = f_text.format(str1)
print(str1)

# Print a message to indicate the addition of leading zeros
print("\nAdded leading zeros:")

# Reset a 'str1' to the original value
str1 = '122.22'

# Define a format text with right alignment and total width of 8
f_text = '{:>08}'

# Use the 'format' method to add leading zeros to 'str1' according to the format text
str1 = f_text.format(str1)
print(str1)

# Define a format text with right alightment and total width of 10
f_text = '{:>010}'

# Repeat the process to make the total width 10
str1 = f_text.format(str1)
print(str1)

Original String:  122.22

Added trailling zeros:
122.2200
122.220000

Added leading zeros:
00122.22
0000122.22


## #130
Write a Python program that uses double quotes to display strings

In [48]:
# Import the 'json' module to work with JSON data
import json
# Create a Python dictionary with key-value pairs
data = {'Alex': 1, 'Suresh': 2, 'Agnessa': 3}

# Use the 'json.dumps()' function to convert the dictionary to a JSON-formatted string and print it
json_string = json.dumps(data)
print(json_string)

{"Alex": 1, "Suresh": 2, "Agnessa": 3}


## #131
Write a Python program to split a variable length string into variables

In [49]:
# Create a list of variables 'x', 'y', and 'z'
var_list = ['a', 'b', 'c']

# Assign the first three elements of 'var_list' to 'x', 'y', and 'z'. Use [None] * 3 to ensure enough elements are available
x, y, z = (var_list + [None] * 3)[:3]

# Print the values of 'x', 'y', and 'z'
print(x, y, z)

# Create a new list of variables 'x', and 'y'
var_list = [100, 20.25]

# Assign the first two elements of 'var_list' to 'x' and 'y'. Use [None] * 2 to ensure enough elements are available
x, y = (var_list + [None] * 2)[:2]

# Print the values of 'x' and 'y'
print(x, y)

a b c
100 20.25


In [50]:
# Create a list 'var_list' containing elements 'a', 'b', 'c', 'd', and 'e'.
var_list = ['a', 'b', 'c', 'd', 'e']

# Assign each element of 'var_list' to variables 'v', 'w', 'x', 'y', and 'z' in that order
v, w, x, y, z = var_list

# Print the values of variables 'v', 'q', 'x', 'y', and 'z'
print(v, w, x, y, z)

a b c d e


## #132
Write a Python program to list the home directory without an absolute path

In [51]:
# Import the 'os.path' module to work with file paths and directories
import os.path
# Use the 'os.path.expanduser()' function to expand the '~' character to the user's home directory
# It returns the absolute path to the user's home directory
print(os.path.expanduser('~'))

/root


## #133
Write a Python program to calculate the time runs (difference between start and current time) of a program

In [52]:
# Import the 'default_timer' function from the 'timeit' module to measure elapsed time
from timeit import default_timer
# Define a function 'timer' that takes an argument 'n'.
def timer(n):
  # Record the current time using the 'default_timer' function
  start = default_timer()

  # Some code here (in this case, a loop to print numbers from 0 to 'n')
  for row in range(0, n):
    print(row)

  # Calculate the elapsed time by subtracting the start time from the current time,
  # and print the result.
  print(default_timer() - start)

# Call the 'timer' function with different values of 'n' to measure the execution time
timer(5)
timer(15)

0
1
2
3
4
0.00017207000018970575
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
0.004938605999996071
